[package]
name = "waterui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
waterui-core = { path = "../waterui-core"}
waterui-derive = { path = "../waterui-derive" }