[package]
name = "waterui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
waterui-reactive = { path = "../waterui-reactive" }
waterui-core = { path = "../waterui-core" }

[dependencies.url]
version = "2.5.0"
optional = true

[dependencies.serde]
version = "1.0.193"
default-features = false
features = ["derive"]
optional = true

[features]
default = ["remote-image"]
std = []
all = ["remote-image","serde"]
remote-image = ["dep:url","waterui-reactive/url"]
serde = ["dep:serde"]