[package]
name = "waterui"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
itertools = "0.12.0"
url = "2.4.1"
waterui-derive = {path = "../waterui-derive"}
waterui-core = {path="../waterui-core"}