[package]
name = "waterui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
itertools = "0.12.0"
pin-project-lite = "0.2.13"
smol = "1.3.0"
url = "2.5.0"
waterui-core = { path = "../waterui-core"}
waterui-derive = { path = "../waterui-derive" }
