language = "C"
[enum]
prefix_with_name = true

[export]
include = ["App","AppClosure"]


[parse]
parse_deps = true
include = ["waterui","waterui-ffi"]
extra_bindings = ["waterui-ffi"]


[parse.expand]
crates = ["waterui","waterui-ffi"]