[package]
name = "waterui-map"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "../../../README.md"
repository.workspace = true
description = "Map component for WaterUI framework"
keywords = ["map", "mapkit", "location", "ui", "waterui"]
categories = ["gui"]

[dependencies]
waterui-core.workspace = true
waterui-str.workspace = true
waterkit-location.workspace = true
nami.workspace = true

[dev-dependencies]
waterui = { path = "../../.." }
waterui-testing = { path = "../../../testing" }

[lints]
workspace = true
