#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
IMAGE="waterui-hydrolysis-wayland-smoke:latest"
DOCKERFILE="${ROOT_DIR}/backends/hydrolysis/scripts/wayland-smoke.Dockerfile"
INNER_SCRIPT="/work/backends/hydrolysis/scripts/wayland_docker_smoke_inner.sh"
EXAMPLE="${HYDROLYSIS_WAYLAND_EXAMPLE:-wayland_smoke}"
ARTIFACT="${HYDROLYSIS_WAYLAND_ARTIFACT:-${EXAMPLE}}"
RUN_SECONDS="${HYDROLYSIS_WAYLAND_SECONDS:-15}"
OUTPUT_WIDTH="${HYDROLYSIS_WAYLAND_OUTPUT_WIDTH:-1920}"
OUTPUT_HEIGHT="${HYDROLYSIS_WAYLAND_OUTPUT_HEIGHT:-1080}"
OUTPUT_SCALE="${HYDROLYSIS_WAYLAND_OUTPUT_SCALE:-1}"
WGPU_BACKEND="${HYDROLYSIS_WAYLAND_WGPU_BACKEND:-gles}"

docker build -f "${DOCKERFILE}" -t "${IMAGE}" "${ROOT_DIR}"

docker run --rm -t \
    -v "${ROOT_DIR}:/work" \
    -w /work \
    -e HYDROLYSIS_WAYLAND_EXAMPLE="${EXAMPLE}" \
    -e HYDROLYSIS_WAYLAND_ARTIFACT="${ARTIFACT}" \
    -e HYDROLYSIS_WAYLAND_SECONDS="${RUN_SECONDS}" \
    -e HYDROLYSIS_WAYLAND_OUTPUT_WIDTH="${OUTPUT_WIDTH}" \
    -e HYDROLYSIS_WAYLAND_OUTPUT_HEIGHT="${OUTPUT_HEIGHT}" \
    -e HYDROLYSIS_WAYLAND_OUTPUT_SCALE="${OUTPUT_SCALE}" \
    -e HYDROLYSIS_WAYLAND_WGPU_BACKEND="${WGPU_BACKEND}" \
    "${IMAGE}" \
    bash "${INNER_SCRIPT}"
