[package]
name = "chromium-example"
version = "0.1.0"
edition = "2024"
authors = ["Lexo Liu"]
description = "Advanced Chromium and CDP example for WaterUI"
license.workspace = true
repository.workspace = true
keywords = ["ui", "framework", "example", "chromium", "cdp"]
categories = ["gui", "web-programming"]
publish = false

[features]
dev = ["waterui/dynamic_linking"]

[dependencies]
serde_json = "1.0"
waterui.workspace = true
waterui-browser-cef = { workspace = true, features = ["chromium"] }
waterui-chromium.workspace = true

[lints]
workspace = true
