//! Shared definitions for the corpus generator binaries (`generator` feature).
//!
//! [`FONTS`] lists the OFL-licensed fonts the corpus is built with, the text
//! each covers, and the file names used in `scenes/fonts/`. Full fonts live in
//! `scenes/fonts/_full/` (not committed); `prepare-fonts` subsets them down to
//! the corpus texts with [skera](https://github.com/googlefonts/skera), and
//! `generate-corpus` shapes the texts with parley against the subsets.

use std::path::{Path, PathBuf};

use read_fonts::FontRef;
use read_fonts::collections::IntSet;
use read_fonts::tables::name::NameId;
use read_fonts::types::{GlyphId, Tag};
use skera::{
    DEFAULT_LAYOUT_FEATURES, DSIG, EBSC, GLAT, GLOC, JSTF, KERN, KERX, LTSH, MORT, MORX, PCLT,
    Plan, SILF, SILL, SubsetError, SubsetFlags, subset_font,
};

/// Re-exports used by the corpus binaries.
pub use read_fonts;

/// A corpus font: where the full file lives, where the subset goes, and which
/// corpus text it must cover.
#[derive(Debug)]
pub struct FontSpec {
    /// File name of the subset inside `scenes/fonts/`.
    pub subset_file: &'static str,
    /// File name of the full font inside `scenes/fonts/_full/`.
    pub full_file: &'static str,
    /// The corpus text shaped with this font.
    pub text: &'static str,
}

/// Latin sample text (Noto Sans).
pub const LATIN: &str = "The quick brown fox jumps over the lazy dog 0123456789!?";
/// Simplified Chinese sample text (Noto Sans SC).
pub const CJK: &str = "。，0123456789";
/// Arabic sample text (Noto Sans Arabic, RTL with joining).
pub const ARABIC: &str = "مرحبا بالعالم! أهلا وسهلا ١٢٣";
/// Hebrew sample text (Noto Sans Hebrew, RTL).
pub const HEBREW: &str = "שלום עולם! 123";
/// Devanagari sample text (Noto Sans Devanagari, conjuncts and marks).
pub const DEVANAGARI: &str = "नमस्ते दुनिया! क्षत्रिय १२३";
/// Thai sample text (Noto Sans Thai, combining marks).
pub const THAI: &str = "สวัสดีชาวโลก ๑๒๓";
/// Emoji sample text (Noto Emoji, monochrome outlines).
pub const EMOJI: &str = "😀🎨🚀❤";
/// `COLRv1` sample text (Nabla).
pub const COLR: &str = "AZ9";
/// Bitmap colour fonts used by the bitmap-rendering scenes.
pub const BITMAP_FONTS: &[&str] = &["NotoColorEmojiSubset.ttf", "CherenkovSbixTest.ttf"];
/// Emoji covered by the CBDT and sbix fixtures.
pub const BITMAP_EMOJI: &str = "\u{2615}\u{26A0}\u{26A1}\u{2764}\u{1F600}";

/// The corpus fonts. All are OFL-licensed; `scenes/fonts/OFL.txt` is the
/// shared licence file kept next to them.
pub const FONTS: &[FontSpec] = &[
    FontSpec {
        subset_file: "NotoSans.ttf",
        full_file: "NotoSans_wdth_wght_.ttf",
        text: LATIN,
    },
    FontSpec {
        subset_file: "NotoSansSC.ttf",
        full_file: "NotoSansSC_wght_.ttf",
        text: CJK,
    },
    FontSpec {
        subset_file: "NotoSansArabic.ttf",
        full_file: "NotoSansArabic_wdth_wght_.ttf",
        text: ARABIC,
    },
    FontSpec {
        subset_file: "NotoSansHebrew.ttf",
        full_file: "NotoSansHebrew_wdth_wght_.ttf",
        text: HEBREW,
    },
    FontSpec {
        subset_file: "NotoSansDevanagari.ttf",
        full_file: "NotoSansDevanagari_wdth_wght_.ttf",
        text: DEVANAGARI,
    },
    FontSpec {
        subset_file: "NotoSansThai.ttf",
        full_file: "NotoSansThai_wdth_wght_.ttf",
        text: THAI,
    },
    FontSpec {
        subset_file: "NotoEmoji.ttf",
        full_file: "NotoEmoji_wght_.ttf",
        text: EMOJI,
    },
    FontSpec {
        subset_file: "Nabla.ttf",
        full_file: "Nabla_EDPT_EHLT_.ttf",
        text: COLR,
    },
];

/// The licence file kept next to the subsets.
pub const LICENSE_FILE: &str = "OFL.txt";

/// Fonts the corpus registers whole, without subsetting.
///
/// These are generated test fonts carrying features no OFL sample font
/// exercises. `CherenkovColrTest.ttf` and `CherenkovWindingTest.ttf` are
/// generated by `scenes/fonts/tools/build_colr_test_font.py` and
/// `scenes/fonts/tools/build_winding_test_font.py` (Apache-2.0 OR MIT).
/// `CherenkovStaticSans.ttf`, the Noto Sans subset pinned to its regular
/// instance by `scenes/fonts/tools/build_static_test_font.py`, is a
/// single face with no weight axis, so a bold request synthesizes the
/// weight (OFL, like its source).
pub const TEST_FONTS: &[&str] = &[
    "CherenkovColrTest.ttf",
    "CherenkovWindingTest.ttf",
    "CherenkovStaticSans.ttf",
];

/// All scalar values the corpus texts use, as an [`IntSet`] for skera.
///
/// Subsetting per font to the union of every corpus text is safe: the cmap
/// closure in [`Plan::new`] retains only characters the font actually maps.
#[must_use]
pub fn corpus_unicodes() -> IntSet<u32> {
    let mut set = IntSet::empty();
    for spec in FONTS {
        for ch in spec.text.chars() {
            set.insert(u32::from(ch));
        }
    }
    // Printable ASCII so variable-font scenes can freely mix in ASCII.
    set.insert_range(0x20..=0x7e);
    set
}

/// Errors from [`subset`].
#[derive(Debug, thiserror::Error)]
pub enum SubsetFontError {
    /// The source font failed to parse.
    #[error("invalid font: {0}")]
    Parse(#[from] read_fonts::ReadError),
    /// skera failed to produce the subset.
    #[error("subset failed: {0}")]
    Subset(#[from] SubsetError),
}

/// Subset `font_bytes` down to the corpus unicodes, without hinting.
///
/// Mirrors the defaults of skera's own CLI (`skera --no-hinting`): the default
/// drop-table set, all layout scripts, the default layout features, name IDs
/// 0–6 in `en-US`, and the standard no-subset table list.
///
/// # Errors
/// [`SubsetFontError`] on parse or subsetting failure.
pub fn subset(font_bytes: &[u8]) -> Result<Vec<u8>, SubsetFontError> {
    let font = FontRef::new(font_bytes)?;

    let flags = SubsetFlags::SUBSET_FLAGS_NO_HINTING;

    // Same default drop-table list as skera's CLI (Harfbuzz hb-subset-input
    // defaults plus the Graphite and bitmap tables).
    let drop_tables: IntSet<Tag> = [
        MORX,
        MORT,
        KERX,
        KERN,
        JSTF,
        DSIG,
        Tag::new(b"EBDT"),
        Tag::new(b"EBLC"),
        EBSC,
        Tag::new(b"svg "),
        PCLT,
        LTSH,
        Tag::new(b"feat"),
        GLAT,
        GLOC,
        SILF,
        SILL,
    ]
    .iter()
    .copied()
    .collect();

    let mut layout_scripts = IntSet::<Tag>::empty();
    layout_scripts.invert();

    let mut layout_features = IntSet::<Tag>::empty();
    layout_features.extend(DEFAULT_LAYOUT_FEATURES.iter().copied());

    let mut name_ids = IntSet::<NameId>::empty();
    name_ids.insert_range(NameId::from(0)..=NameId::from(6));
    let mut name_languages = IntSet::<u16>::empty();
    name_languages.insert(0x0409);

    let gids = IntSet::<GlyphId>::empty();
    let unicodes = corpus_unicodes();
    let plan = Plan::new(
        &gids,
        &unicodes,
        &font,
        flags,
        &drop_tables,
        &layout_scripts,
        &layout_features,
        &name_ids,
        &name_languages,
    );
    Ok(subset_font(&font, &plan)?)
}

/// The directory holding the full (uncommitted) fonts.
#[must_use]
pub fn full_fonts_dir(root: &Path) -> PathBuf {
    root.join("scenes/fonts/_full")
}

/// The directory holding the subset fonts shipped with the corpus.
#[must_use]
pub fn fonts_dir(root: &Path) -> PathBuf {
    root.join("scenes/fonts")
}

/// The corpus output directory.
#[must_use]
pub fn corpus_dir(root: &Path) -> PathBuf {
    root.join("scenes/corpus")
}

/// The performance set's output directory — full-resolution scenes,
/// separate from the per-primitive correctness sweeps in [`corpus_dir`].
#[must_use]
pub fn perf_dir(root: &Path) -> PathBuf {
    root.join("scenes/perf")
}

/// The repository root, resolved from `CARGO_MANIFEST_DIR` (the `scene`
/// crate's directory).
#[must_use]
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace layout")
        .to_path_buf()
}
