#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Regenerate the test font in this directory from a pinned upstream source.

The CLI's font tests copy this file into fixture projects at run time —
`cargo nextest run -p waterui-cli` produces it through the package's setup
script, and a manual run needs it first:

    uv run cli/tests/fixtures/fonts/generate.py

The downloaded archive is pinned by URL and verified by SHA-256, and the
font written into this directory is verified against its expected SHA-256 —
the generated bytes are part of the test contract, so a drifted output is a
hard failure, never a silent regeneration. The font itself is a binary asset
and stays out of the repository (see the repository's no-binary-assets
rule); `tests/fixtures/fonts/*.ttf` is gitignored.

`Roboto-Regular.ttf` is the unmodified member of the googlefonts/roboto
v2.138 `roboto-android.zip` release — the same pinned source Hydrolysis's
`test-fonts/install.py` draws its Roboto faces from — under the Apache 2.0
licence kept beside it as `LICENSE`.
"""

from __future__ import annotations

import hashlib
import io
import sys
import urllib.request
import zipfile
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

ARCHIVE_URL = "https://github.com/googlefonts/roboto/releases/download/v2.138/roboto-android.zip"
ARCHIVE_SHA256 = "c825453253f590cfe62557733e7173f9a421fff103b00f57d33c4ad28ae53baf"
EXPECTED = {
    "Roboto-Regular.ttf": "797e35f7f5d6020a5c6ea13b42ecd668bcfb3bbc4baa0e74773527e5b6cb3174",
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def fetch(url: str, expected_sha256: str) -> bytes:
    """Download `url` and verify its SHA-256."""
    print(f"fetch {url}")
    data = None
    for attempt in range(4):
        try:
            data = urllib.request.urlopen(url, timeout=120).read()
            break
        except Exception as error:  # noqa: BLE001 — report and retry, pin wins
            if attempt == 3:
                raise SystemExit(f"fetch {url} failed after 4 attempts: {error}")
            import time

            time.sleep(2**attempt * 2)
    digest = sha256(data)
    if digest != expected_sha256:
        raise SystemExit(
            f"sha256 mismatch for {url}:\n  got      {digest}\n  expected {expected_sha256}"
        )
    return data


def main() -> None:
    out = OUT_DIR / "Roboto-Regular.ttf"
    if out.is_file():
        digest = sha256(out.read_bytes())
        if digest == EXPECTED["Roboto-Regular.ttf"]:
            print(f"Roboto-Regular.ttf already generated ({digest[:12]}…)")
            return
        raise SystemExit(
            f"Roboto-Regular.ttf: existing sha256 {digest} != expected "
            f"{EXPECTED['Roboto-Regular.ttf']}\n"
            "the font bytes are part of the test contract — remove the file "
            "and rerun, or investigate why it drifted"
        )
    archive = fetch(ARCHIVE_URL, ARCHIVE_SHA256)
    with zipfile.ZipFile(io.BytesIO(archive)) as zf:
        data = zf.read("Roboto-Regular.ttf")
    digest = sha256(data)
    if digest != EXPECTED["Roboto-Regular.ttf"]:
        raise SystemExit(
            f"Roboto-Regular.ttf: generated sha256 {digest} != expected "
            f"{EXPECTED['Roboto-Regular.ttf']}\n"
            "the font bytes are part of the test contract — investigate the "
            "source drift instead of accepting the output"
        )
    (OUT_DIR / "Roboto-Regular.ttf").write_bytes(data)
    print(f"  wrote Roboto-Regular.ttf ({len(data)} bytes, {digest[:12]}…)")


if __name__ == "__main__":
    sys.exit(main())
