[package]
name = "waterui-str"
version = "0.1.0"
edition = "2024"

[dependencies]
uniffi = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["ffi"]
std = []
ffi = ["dep:uniffi", "std"]
serde = ["dep:serde"]
