[package]
name = "waterui-str"
version = "0.1.0"
edition = "2024"

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]
optional = true

[dependencies]
waterui-ffi.workspace = true

[features]

serde = ["dep:serde"]
