waterui_path = "../.."
webview_backend = "cef"

[package]
type = "playground"
name = "CEF WebView Example"
bundle_identifier = "dev.waterui.examples.webviewcef"

[permissions.internet]
enable = true
description = "Required to access web content from the internet"
