[package]
name = "waterui-task"
version = "0.1.0"
edition = "2024"

[dependencies]
async-task = "4.7.1"
futures-lite = "2.6"
spin = "0.10"

[target.'cfg(target_vendor = "apple")'.dependencies]
dispatch = "0.2.0"
