pub const BUTTON_MIN_WIDTH: f64 = 64.0;
pub const BUTTON_MIN_HEIGHT: f64 = 56.0;
pub const BUTTON_CONTAINER_RADIUS: f64 = 28.0;
pub const BUTTON_TEXT_HORIZONTAL_PADDING: f64 = 24.0;
pub const BUTTON_TEXT_VERTICAL_PADDING: f64 = 10.0;
pub const BUTTON_LINK_UNDERLINE_BOTTOM_INSET: f64 = 2.0;
pub const BUTTON_LINK_UNDERLINE_THICKNESS: f64 = 1.0;
pub const BUTTON_LINK_HORIZONTAL_PADDING: f64 = 12.0;
pub const BUTTON_LINK_VERTICAL_PADDING: f64 = 10.0;

pub const TOGGLE_SWITCH_WIDTH: f64 = 52.0;
pub const TOGGLE_SWITCH_HEIGHT: f64 = 32.0;
pub const TOGGLE_SWITCH_OUTLINE_WIDTH: f64 = 2.0;
pub const TOGGLE_SWITCH_UNSELECTED_HANDLE_SIZE: f64 = 16.0;
pub const TOGGLE_SWITCH_SELECTED_HANDLE_SIZE: f64 = 24.0;
pub const TOGGLE_SWITCH_PRESSED_HANDLE_SIZE: f64 = 28.0;
pub const TOGGLE_CHECKBOX_SIZE: f64 = 18.0;
pub const TOGGLE_CHECKBOX_CONTAINER_SHAPE: f64 = 2.0;
pub const TOGGLE_CHECKBOX_OUTLINE_WIDTH: f64 = 2.0;
pub const TOGGLE_CHECKBOX_SELECTED_SCALE_START: f64 = 0.6;

pub const STEPPER_BUTTON_MIN_SIZE: f64 = 24.0;
pub const STEPPER_BUTTON_MAX_SIZE: f64 = 32.0;
pub const STEPPER_BUTTON_INTRINSIC_SIZE: f64 = 28.0;

pub const INPUT_LABEL_HEIGHT: f64 = 18.0;
pub const INPUT_FIELD_MIN_WIDTH: f64 = 72.0;
pub const INPUT_FIELD_MIN_HEIGHT: f64 = 56.0;
pub const INPUT_FIELD_HORIZONTAL_INSET: f64 = 16.0;
pub const INPUT_FIELD_VERTICAL_INSET: f64 = 8.0;
pub const INPUT_FILLED_CONTAINER_TOP_RADIUS: f64 = 4.0;
pub const INPUT_FILLED_ACTIVE_INDICATOR_HEIGHT: f64 = 1.0;
pub const INPUT_FILLED_FOCUS_ACTIVE_INDICATOR_HEIGHT: f64 = 2.0;

pub const PICKER_MIN_WIDTH: f64 = 72.0;
pub const PICKER_MIN_HEIGHT: f64 = 56.0;
pub const PICKER_HORIZONTAL_INSET: f64 = 16.0;
pub const PICKER_VERTICAL_INSET: f64 = 8.0;
pub const PICKER_INDICATOR_SPACE: f64 = 18.0;
pub const PICKER_RADIO_INDICATOR_SIZE: f64 = 20.0;
pub const PICKER_RADIO_OUTER_RING_WIDTH: f64 = 2.0;
pub const PICKER_RADIO_INNER_DOT_RADIUS: f64 = 5.0;
pub const PICKER_RADIO_LABEL_SPACING: f64 = 8.0;
pub const PICKER_RADIO_ROW_SPACING: f64 = 6.0;
pub const PICKER_MENU_POPUP_TOP_SPACING: f64 = 4.0;
pub const PICKER_MENU_POPUP_ROW_HEIGHT: f64 = 48.0;
pub const PICKER_MENU_POPUP_CORNER_RADIUS: f64 = 4.0;

pub const SLIDER_HORIZONTAL_INSET: f64 = 12.0;
pub const SLIDER_HORIZONTAL_SPACING: f64 = 8.0;
pub const SLIDER_VERTICAL_SPACING: f64 = 6.0;
pub const SLIDER_MIN_TRACK_WIDTH: f64 = 72.0;
pub const SLIDER_TRACK_HEIGHT: f64 = 16.0;
pub const SLIDER_HANDLE_WIDTH: f64 = 4.0;
pub const SLIDER_PRESSED_HANDLE_WIDTH: f64 = 2.0;
pub const SLIDER_HANDLE_HEIGHT: f64 = 44.0;
pub const SLIDER_STATE_LAYER_RADIUS: f64 = 20.0;

pub const PROGRESS_LINEAR_LABEL_HEIGHT: f64 = 18.0;
pub const PROGRESS_LINEAR_BAR_TOP_OFFSET: f64 = 10.0;
pub const PROGRESS_LINEAR_BAR_HEIGHT: f64 = 4.0;
pub const PROGRESS_LINEAR_BAR_HORIZONTAL_INSET: f64 = 8.0;
pub const PROGRESS_LINEAR_VALUE_LABEL_TOP_SPACING: f64 = 6.0;
pub const PROGRESS_LINEAR_MIN_TRACK_WIDTH: f64 = 80.0;
pub const PROGRESS_CIRCULAR_DIAMETER: f64 = 48.0;
pub const PROGRESS_CIRCULAR_STROKE_WIDTH: f64 = 4.0;

pub const NAVIGATION_BAR_CORNER_RADIUS: f64 = 6.0;
pub const SCROLL_INDICATOR_CORNER_RADIUS: f64 = 1.25;
pub const TABS_BAR_HEIGHT: f64 = 48.0;
pub const TABS_ACTIVE_INDICATOR_HEIGHT: f64 = 3.0;
pub const TABS_ACTIVE_INDICATOR_RADIUS: f64 = 3.0;
pub const LIST_ONE_LINE_ROW_HEIGHT: f64 = 56.0;
pub const LIST_HORIZONTAL_INSET: f64 = 16.0;
pub const LIST_VERTICAL_INSET: f64 = 10.0;
pub const LIST_DIVIDER_LEADING_INSET: f64 = 16.0;
pub const LIST_DIVIDER_TRAILING_INSET: f64 = 16.0;
pub const LIST_CONTROL_CORNER_RADIUS: f64 = 5.0;
