[package]
name = "waterui-task"
version = "0.1.0"
edition = "2021"

[dependencies]
async-task = "4.7.1"
futures-lite = "2.3.0"
spin = "0.9.8"

[target.'cfg(target_vendor = "apple")'.dependencies]
dispatch = "0.2.0"