//! JNI component functions for WaterUI Android.
//!
//! This module provides JNI functions for actions, theme, layout, and other
//! component-related operations.
//!
//! NOTE: Most drop functions are auto-generated by the opaque! macro.
//! This file only contains functions NOT generated by macros.

extern crate alloc;
extern crate std;

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec::Vec;
#[cfg(target_os = "android")]
use core::ffi::c_void;

use jni::JNIEnv;
use jni::objects::{GlobalRef, JClass, JObject, JString, JValue};
use jni::sys::{jboolean, jfloat, jint, jintArray, jlong, jobject, jobjectArray};
use nami::SignalExt;
use waterui_layout::{Layout, ProposalSize, Rect, Size, StretchAxis, SubView};

use crate::IntoFFI;
use crate::IntoRust;
use crate::components::layout::WuiLayout;
use waterui_graphics::color::ResolvedColor;
use waterui_text::font::{FontWeight, ResolvedFont};

#[cfg(target_os = "android")]
use ndk::hardware_buffer::HardwareBuffer;
#[cfg(target_os = "android")]
use ndk_sys::ANativeWindow;

#[cfg(target_os = "android")]
struct AndroidNativeWindow {
    ptr: *mut ANativeWindow,
}

#[cfg(target_os = "android")]
impl AndroidNativeWindow {
    unsafe fn from_surface(env: *mut jni::sys::JNIEnv, surface: jobject) -> Option<Self> {
        let ptr = unsafe { ndk_sys::ANativeWindow_fromSurface(env, surface) };
        (!ptr.is_null()).then_some(Self { ptr })
    }

    fn as_void_ptr(&self) -> *mut c_void {
        self.ptr.cast::<c_void>()
    }
}

#[cfg(target_os = "android")]
impl Drop for AndroidNativeWindow {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe { ndk_sys::ANativeWindow_release(self.ptr) };
        }
    }
}

// ============================================================================
// Action Call Functions (drop functions are generated by opaque! macro)
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callAction<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    action_ptr: jlong,
    env_ptr: jlong,
) {
    let action = action_ptr as *mut crate::action::WuiAction;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::action::waterui_call_action(action, wui_env) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callSharedAction<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    action_ptr: jlong,
    env_ptr: jlong,
) {
    let action = action_ptr as *mut crate::action::WuiAction;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::action::waterui_call_action(action, wui_env) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gestureFromPtr<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    gesture_ptr: jlong,
) -> jobject {
    use crate::jni::convert::jlong_to_ptr;
    if gesture_ptr == 0 {
        return JObject::null().into_raw();
    }
    let gesture = unsafe { jlong_to_ptr::<crate::gesture::WuiGesture>(gesture_ptr) };
    let gesture = unsafe { &*gesture };
    crate::jni::convert::struct_to_java(&mut env, gesture).into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropGesture<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    gesture_ptr: jlong,
) {
    use crate::jni::convert::jlong_to_ptr_mut;
    if gesture_ptr == 0 {
        return;
    }
    let gesture = unsafe { jlong_to_ptr_mut::<crate::gesture::WuiGesture>(gesture_ptr) };
    unsafe { crate::gesture::waterui_drop_gesture(gesture) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callIndexAction<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    action_ptr: jlong,
    env_ptr: jlong,
    index: jlong,
) {
    let action = action_ptr as *mut crate::action::WuiIndexAction;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::action::waterui_call_index_action(action, wui_env, index as usize) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callMoveAction<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    action_ptr: jlong,
    env_ptr: jlong,
    from_index: jlong,
    to_index: jlong,
) {
    let action = action_ptr as *mut crate::action::WuiMoveAction;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe {
        crate::action::waterui_call_move_action(
            action,
            wui_env,
            from_index as usize,
            to_index as usize,
        )
    };
}

// ============================================================================
// Layout Functions (drop function is generated by opaque! macro)
// ============================================================================

/// JNI SubView wrapper that calls back to Java for measurement.
struct JniSubView {
    /// Global reference to the Java SubViewStruct object
    subview_ref: GlobalRef,
    /// Stretch axis for layout
    stretch_axis: StretchAxis,
    /// Layout priority
    priority: i32,
}

impl SubView for JniSubView {
    fn size_that_fits(&self, proposal: ProposalSize) -> Size {
        // Attach to JVM (may already be attached on main thread)
        let vm = super::java_vm();
        let mut env = vm.attach_current_thread().expect("Failed to attach to JVM");

        let width = proposal.width.unwrap_or(f32::NAN);
        let height = proposal.height.unwrap_or(f32::NAN);

        let size_obj = env
            .call_method(
                &self.subview_ref,
                "measureForLayout",
                "(FF)Ldev/waterui/android/runtime/SizeStruct;",
                &[JValue::Float(width), JValue::Float(height)],
            )
            .expect("measureForLayout call failed")
            .l()
            .expect("measureForLayout should return object");
        // Extract width and height from SizeStruct
        let w = env
            .get_field(&size_obj, "width", "F")
            .expect("SizeStruct.width")
            .f()
            .expect("width is float");
        let h = env
            .get_field(&size_obj, "height", "F")
            .expect("SizeStruct.height")
            .f()
            .expect("height is float");
        Size {
            width: w,
            height: h,
        }
    }

    fn stretch_axis(&self) -> StretchAxis {
        self.stretch_axis
    }

    fn priority(&self) -> i32 {
        self.priority
    }
}

/// Extract ProposalStruct from Java object
fn extract_proposal(env: &mut JNIEnv, proposal: &JObject) -> ProposalSize {
    let width = env
        .get_field(proposal, "width", "F")
        .expect("ProposalStruct.width")
        .f()
        .expect("width is float");
    let height = env
        .get_field(proposal, "height", "F")
        .expect("ProposalStruct.height")
        .f()
        .expect("height is float");

    ProposalSize {
        width: if width.is_finite() { Some(width) } else { None },
        height: if height.is_finite() {
            Some(height)
        } else {
            None
        },
    }
}

/// Extract RectStruct from Java object
fn extract_rect(env: &mut JNIEnv, rect: &JObject) -> Rect {
    let x = env
        .get_field(rect, "x", "F")
        .expect("RectStruct.x")
        .f()
        .expect("x is float");
    let y = env
        .get_field(rect, "y", "F")
        .expect("RectStruct.y")
        .f()
        .expect("y is float");
    let width = env
        .get_field(rect, "width", "F")
        .expect("RectStruct.width")
        .f()
        .expect("width is float");
    let height = env
        .get_field(rect, "height", "F")
        .expect("RectStruct.height")
        .f()
        .expect("height is float");

    unsafe { Rect::new(waterui_layout::Point { x, y }, Size { width, height }) }
}

/// Convert StretchAxis int to Rust enum
fn stretch_axis_from_ordinal(ordinal: i32) -> StretchAxis {
    match ordinal {
        0 => StretchAxis::None,
        1 => StretchAxis::Horizontal,
        2 => StretchAxis::Vertical,
        3 => StretchAxis::Both,
        4 => StretchAxis::MainAxis,
        5 => StretchAxis::CrossAxis,
        _ => StretchAxis::None,
    }
}

/// Extract SubViewStruct array and create JniSubView wrappers
fn extract_subviews(env: &mut JNIEnv, subviews_array: jobjectArray) -> Vec<JniSubView> {
    let array_obj = unsafe { jni::objects::JObjectArray::from_raw(subviews_array) };
    let len = env.get_array_length(&array_obj).expect("get array length");

    let mut result = Vec::with_capacity(len as usize);

    for i in 0..len {
        let subview_obj = env
            .get_object_array_element(&array_obj, i)
            .expect("get array element");

        // Get stretchAxis enum ordinal
        let stretch_axis_obj = env
            .get_field(
                &subview_obj,
                "stretchAxis",
                "Ldev/waterui/android/runtime/StretchAxis;",
            )
            .expect("SubViewStruct.stretchAxis")
            .l()
            .expect("stretchAxis is object");
        let stretch_ordinal = env
            .call_method(&stretch_axis_obj, "ordinal", "()I", &[])
            .expect("ordinal()")
            .i()
            .expect("ordinal is int");

        // Get priority
        let priority = env
            .get_field(&subview_obj, "priority", "I")
            .expect("SubViewStruct.priority")
            .i()
            .expect("priority is int");

        // Create global ref to keep the object alive
        let global_ref = env.new_global_ref(&subview_obj).expect("create global ref");

        result.push(JniSubView {
            subview_ref: global_ref,
            stretch_axis: stretch_axis_from_ordinal(stretch_ordinal),
            priority,
        });
    }

    result
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_layoutSizeThatFits<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    layout_ptr: jlong,
    proposal: JObject<'local>,
    subviews: jobjectArray,
) -> jobject {
    let layout: &dyn Layout = unsafe { &*(*(layout_ptr as *mut WuiLayout)).0 };
    let proposal = extract_proposal(&mut env, &proposal);

    let jni_subviews = extract_subviews(&mut env, subviews);

    // Create trait object references
    let subview_refs: Vec<&dyn SubView> = jni_subviews.iter().map(|s| s as &dyn SubView).collect();

    let size = layout.size_that_fits(proposal, &subview_refs);

    // Create SizeStruct result
    let class = env
        .find_class("dev/waterui/android/runtime/SizeStruct")
        .expect("SizeStruct class");
    let result = env
        .new_object(
            &class,
            "(FF)V",
            &[JValue::Float(size.width), JValue::Float(size.height)],
        )
        .expect("create SizeStruct");

    result.into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_layoutPlace<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    layout_ptr: jlong,
    bounds: JObject<'local>,
    subviews: jobjectArray,
) -> jobjectArray {
    let layout: &dyn Layout = unsafe { &*(*(layout_ptr as *mut WuiLayout)).0 };
    let bounds = extract_rect(&mut env, &bounds);

    let jni_subviews = extract_subviews(&mut env, subviews);

    // Create trait object references
    let subview_refs: Vec<&dyn SubView> = jni_subviews.iter().map(|s| s as &dyn SubView).collect();

    let rects = layout.place(bounds, &subview_refs);

    // Create RectStruct array result
    let rect_class = env
        .find_class("dev/waterui/android/runtime/RectStruct")
        .expect("RectStruct class");

    let result_array = env
        .new_object_array(rects.len() as i32, &rect_class, JObject::null())
        .expect("create RectStruct array");

    for (i, rect) in rects.iter().enumerate() {
        let rect_obj = env
            .new_object(
                &rect_class,
                "(FFFF)V",
                &[
                    JValue::Float(rect.x()),
                    JValue::Float(rect.y()),
                    JValue::Float(rect.width()),
                    JValue::Float(rect.height()),
                ],
            )
            .expect("create RectStruct");

        env.set_object_array_element(&result_array, i as i32, rect_obj)
            .expect("set array element");
    }

    result_array.into_raw()
}

// ============================================================================
// Theme Functions
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorBackground<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_background(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorSurface<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_surface(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorSurfaceVariant<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_surface_variant(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorBorder<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_border(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorForeground<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_foreground(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorMutedForeground<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_muted_foreground(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorAccent<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_accent(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorAccentForeground<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_accent_foreground(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFontBody<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_font_body(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFontTitle<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_font_title(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFontHeadline<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_font_headline(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFontSubheadline<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_font_subheadline(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFontCaption<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_font_caption(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFontFootnote<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_font_footnote(wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeInstallColor<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
    slot: jint,
    signal_ptr: jlong,
) {
    let wui_env = env_ptr as *mut crate::WuiEnv;
    let slot = match slot {
        0 => crate::theme::WuiColorSlot::Background,
        1 => crate::theme::WuiColorSlot::Surface,
        2 => crate::theme::WuiColorSlot::SurfaceVariant,
        3 => crate::theme::WuiColorSlot::Border,
        4 => crate::theme::WuiColorSlot::Foreground,
        5 => crate::theme::WuiColorSlot::MutedForeground,
        6 => crate::theme::WuiColorSlot::Accent,
        _ => crate::theme::WuiColorSlot::AccentForeground,
    };
    let signal =
        signal_ptr as *mut crate::reactive::WuiComputed<waterui_graphics::color::ResolvedColor>;
    unsafe { crate::theme::waterui_theme_install_color(wui_env, slot, signal) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeInstallFont<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
    slot: jint,
    signal_ptr: jlong,
) {
    let wui_env = env_ptr as *mut crate::WuiEnv;
    let slot = match slot {
        0 => crate::theme::WuiFontSlot::Body,
        1 => crate::theme::WuiFontSlot::Title,
        2 => crate::theme::WuiFontSlot::Headline,
        3 => crate::theme::WuiFontSlot::Subheadline,
        4 => crate::theme::WuiFontSlot::Caption,
        _ => crate::theme::WuiFontSlot::Footnote,
    };
    let signal = signal_ptr as *mut crate::reactive::WuiComputed<waterui_text::font::ResolvedFont>;
    unsafe { crate::theme::waterui_theme_install_font(wui_env, slot, signal) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeInstallColorScheme<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
    signal_ptr: jlong,
) {
    let wui_env = env_ptr as *mut crate::WuiEnv;
    let signal = signal_ptr as *mut crate::reactive::WuiComputed<waterui::theme::ColorScheme>;
    unsafe { crate::theme::waterui_theme_install_color_scheme(wui_env, signal) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColor<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
    slot: jint,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    let slot = match slot {
        0 => crate::theme::WuiColorSlot::Background,
        1 => crate::theme::WuiColorSlot::Surface,
        2 => crate::theme::WuiColorSlot::SurfaceVariant,
        3 => crate::theme::WuiColorSlot::Border,
        4 => crate::theme::WuiColorSlot::Foreground,
        5 => crate::theme::WuiColorSlot::MutedForeground,
        6 => crate::theme::WuiColorSlot::Accent,
        _ => crate::theme::WuiColorSlot::AccentForeground,
    };
    unsafe { crate::theme::waterui_theme_color(wui_env, slot) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeFont<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
    slot: jint,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    let slot = match slot {
        0 => crate::theme::WuiFontSlot::Body,
        1 => crate::theme::WuiFontSlot::Title,
        2 => crate::theme::WuiFontSlot::Headline,
        3 => crate::theme::WuiFontSlot::Subheadline,
        4 => crate::theme::WuiFontSlot::Caption,
        _ => crate::theme::WuiFontSlot::Footnote,
    };
    unsafe { crate::theme::waterui_theme_font(wui_env, slot) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_themeColorScheme<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jlong {
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::theme::waterui_theme_color_scheme(wui_env) as jlong }
}

// ============================================================================
// Animation Functions
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_getAnimationKindDurationPacked<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    metadata_ptr: jlong,
) -> jlong {
    let metadata = metadata_ptr as *const crate::reactive::WuiWatcherMetadata;
    let animation = unsafe { crate::animation::waterui_get_animation(metadata) };

    let (tag, duration_ms): (u32, u32) = match animation {
        crate::animation::WuiAnimation::None => (0, 0),
        crate::animation::WuiAnimation::Bezier { duration_ms, .. } => {
            (1, duration_ms.min(u64::from(u32::MAX)) as u32)
        }
        crate::animation::WuiAnimation::Spring { .. } => (2, 0),
    };

    ((u64::from(duration_ms) << 32) | u64::from(tag)) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_getAnimationParams12Packed<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    metadata_ptr: jlong,
) -> jlong {
    let metadata = metadata_ptr as *const crate::reactive::WuiWatcherMetadata;
    let animation = unsafe { crate::animation::waterui_get_animation(metadata) };

    let (p1, p2): (f32, f32) = match animation {
        crate::animation::WuiAnimation::Bezier { x1, y1, .. } => (x1, y1),
        crate::animation::WuiAnimation::Spring { stiffness, damping } => (stiffness, damping),
        crate::animation::WuiAnimation::None => (0.0, 0.0),
    };

    ((u64::from(p2.to_bits()) << 32) | u64::from(p1.to_bits())) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_getAnimationParams34Packed<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    metadata_ptr: jlong,
) -> jlong {
    let metadata = metadata_ptr as *const crate::reactive::WuiWatcherMetadata;
    let animation = unsafe { crate::animation::waterui_get_animation(metadata) };

    let (p3, p4): (f32, f32) = match animation {
        crate::animation::WuiAnimation::Bezier { x2, y2, .. } => (x2, y2),
        crate::animation::WuiAnimation::Spring { .. } | crate::animation::WuiAnimation::None => {
            (0.0, 0.0)
        }
    };

    ((u64::from(p4.to_bits()) << 32) | u64::from(p3.to_bits())) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_getAnimation<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    metadata_ptr: jlong,
) -> jint {
    (Java_dev_waterui_android_ffi_WatcherJni_getAnimationKindDurationPacked(
        _env,
        _class,
        metadata_ptr,
    ) as u64
        & 0xffff_ffff) as jint
}

// ============================================================================
// AnyViews Functions (drop function is generated by opaque! macro)
// ============================================================================

struct AnyViewsWatchData {
    jvm: jni::JavaVM,
    callback: GlobalRef,
}

unsafe extern "C" fn anyviews_watch_call(
    data: *mut (),
    ids: crate::array::WuiArray<crate::id::WuiId>,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    // Always release callback payloads from Rust watcher bridge.
    ids.consume();
    if !metadata_ptr.is_null() {
        unsafe { drop(Box::from_raw(metadata_ptr)) };
    }

    debug_assert!(
        !data.is_null(),
        "anyviews_watch_call received null callback payload"
    );
    let watcher_data = unsafe { &*(data as *const AnyViewsWatchData) };

    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("anyviews_watch_call: failed to attach current thread to JVM");
    env.call_method(&watcher_data.callback, "run", "()V", &[])
        .expect("anyviews_watch_call: Java callback run() failed");
}

unsafe extern "C" fn anyviews_watch_drop(data: *mut ()) {
    if !data.is_null() {
        unsafe {
            let _: Box<AnyViewsWatchData> = Box::from_raw(data as *mut AnyViewsWatchData);
        }
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_anyViewsLen<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
) -> jint {
    let anyviews = handle as *const crate::views::WuiAnyViews;
    unsafe { crate::views::waterui_anyviews_len(anyviews) as jint }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_anyViewsGetIdsInRange<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    start: jint,
    end: jint,
) -> jintArray {
    let anyviews = handle as *const crate::views::WuiAnyViews;
    if anyviews.is_null() {
        return core::ptr::null_mut();
    }

    let start = if start.is_negative() {
        0
    } else {
        start as usize
    };
    let end = if end.is_negative() { 0 } else { end as usize };

    let ids = unsafe { crate::views::waterui_anyviews_get_ids_in_range(anyviews, start, end) };
    let rust_ids: Vec<waterui_core::id::Id> = unsafe { crate::IntoRust::into_rust(ids) };
    let values: Vec<jint> = rust_ids.into_iter().map(i32::from).collect();

    let array = env
        .new_int_array(values.len() as jint)
        .expect("anyViewsGetIdsInRange: failed to allocate jintArray");
    env.set_int_array_region(&array, 0, &values)
        .expect("anyViewsGetIdsInRange: failed to write ids into jintArray");

    array.into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_anyViewsGetView<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    index: jint,
) -> jlong {
    let anyviews = handle as *const crate::views::WuiAnyViews;
    unsafe { crate::views::waterui_anyviews_get_view(anyviews, index as usize) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_anyViewsGetId<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    index: jint,
) -> jint {
    let anyviews = handle as *const crate::views::WuiAnyViews;
    let id = unsafe { crate::views::waterui_anyviews_get_id(anyviews, index as usize) };
    // WuiId wraps an i32, return it directly
    id.inner
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_anyViewsWatch<'local>(
    env: JNIEnv<'local>,
    class: JClass<'local>,
    handle: jlong,
    callback: JObject<'local>,
) -> jlong {
    Java_dev_waterui_android_ffi_WatcherJni_anyViewsWatchRange(
        env,
        class,
        handle,
        0,
        jint::MAX,
        callback,
    )
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_anyViewsWatchRange<'local>(
    env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle: jlong,
    start: jint,
    end: jint,
    callback: JObject<'local>,
) -> jlong {
    assert!(
        handle != 0,
        "WatcherJni.anyViewsWatchRange received null AnyViews handle"
    );
    assert!(
        !callback.is_null(),
        "WatcherJni.anyViewsWatchRange received null callback"
    );

    let jvm = env
        .get_java_vm()
        .expect("WatcherJni.anyViewsWatchRange failed to access JavaVM");
    let callback = env
        .new_global_ref(&callback)
        .expect("WatcherJni.anyViewsWatchRange failed to create callback GlobalRef");

    let data = Box::new(AnyViewsWatchData { jvm, callback });
    let data_ptr = Box::into_raw(data) as *mut ();
    let anyviews = handle as *const crate::views::WuiAnyViews;
    let start = if start.is_negative() {
        0
    } else {
        start as usize
    };
    let end = if end.is_negative() { 0 } else { end as usize };
    unsafe {
        crate::views::waterui_anyviews_watch_range(
            anyviews,
            start,
            end,
            data_ptr,
            anyviews_watch_call,
            anyviews_watch_drop,
        ) as jlong
    }
}

// ============================================================================
// Color Functions (drop function is generated by opaque! macro)
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_colorFromSrgba<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    red: jfloat,
    green: jfloat,
    blue: jfloat,
    alpha: jfloat,
) -> jlong {
    unsafe { crate::color::waterui_color_from_srgba(red, green, blue, alpha) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_colorFromLinearRgbaHeadroom<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    red: jfloat,
    green: jfloat,
    blue: jfloat,
    alpha: jfloat,
    headroom: jfloat,
) -> jlong {
    unsafe {
        crate::color::waterui_color_from_linear_rgba_headroom(red, green, blue, alpha, headroom)
            as jlong
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_resolveColor<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    color_ptr: jlong,
    env_ptr: jlong,
) -> jlong {
    let color = color_ptr as *const crate::color::WuiColor;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::color::waterui_resolve_color(color, wui_env) as jlong }
}

// ============================================================================
// Font Functions (drop function is generated by opaque! macro)
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_resolveFont<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    font_ptr: jlong,
    env_ptr: jlong,
) -> jlong {
    let font = font_ptr as *const crate::components::text::WuiFont;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::components::text::waterui_resolve_font(font, wui_env) as jlong }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_fontFromResolved<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    size: jfloat,
    weight: jint,
    family: JString<'local>,
) -> jlong {
    let family = env
        .get_string(&family)
        .expect("WatcherJni.fontFromResolved: failed to read family")
        .to_string_lossy()
        .into_owned();

    let weight = match weight {
        0 => crate::components::text::WuiFontWeight::Thin,
        1 => crate::components::text::WuiFontWeight::UltraLight,
        2 => crate::components::text::WuiFontWeight::Light,
        3 => crate::components::text::WuiFontWeight::Normal,
        4 => crate::components::text::WuiFontWeight::Medium,
        5 => crate::components::text::WuiFontWeight::SemiBold,
        6 => crate::components::text::WuiFontWeight::Bold,
        7 => crate::components::text::WuiFontWeight::UltraBold,
        _ => crate::components::text::WuiFontWeight::Black,
    };

    let family = waterui::Str::from(family).into_ffi();
    unsafe { crate::components::text::waterui_font_from_resolved(size, weight, family) as jlong }
}

// ============================================================================
// Event Handler Functions
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callLifeCycleHook<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handler_ptr: jlong,
    env_ptr: jlong,
) {
    let handler = handler_ptr as *mut crate::event::WuiLifeCycleHookHandler;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::event::waterui_call_lifecycle_hook(handler, wui_env) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropLifeCycleHook<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handler_ptr: jlong,
) {
    unsafe {
        crate::event::waterui_drop_lifecycle_hook(
            handler_ptr as *mut crate::event::WuiLifeCycleHookHandler,
        )
    };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callOnEvent<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handler_ptr: jlong,
    env_ptr: jlong,
) {
    let handler = handler_ptr as *mut crate::event::WuiOnEventHandler;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::event::waterui_call_on_event(handler, wui_env) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropOnEvent<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handler_ptr: jlong,
) {
    unsafe {
        crate::event::waterui_drop_on_event(handler_ptr as *mut crate::event::WuiOnEventHandler)
    };
}

// ============================================================================
// Retain Functions
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropRetain<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    retain_ptr: jlong,
) {
    if retain_ptr == 0 {
        return;
    }
    unsafe { crate::waterui_drop_retain(crate::WuiRetain::from_ptr(retain_ptr as *mut ())) };
}

// ============================================================================
// Reactive State Creation Functions
// ============================================================================

struct ReactiveColorSchemeState {
    binding: waterui::Binding<waterui::theme::ColorScheme>,
}

struct ReactiveColorState {
    binding: waterui::Binding<ResolvedColor>,
}

struct ReactiveFontState {
    binding: waterui::Binding<ResolvedFont>,
}

fn font_weight_from_ordinal(ordinal: jint) -> FontWeight {
    match ordinal {
        0 => FontWeight::Thin,
        1 => FontWeight::UltraLight,
        2 => FontWeight::Light,
        3 => FontWeight::Normal,
        4 => FontWeight::Medium,
        5 => FontWeight::SemiBold,
        6 => FontWeight::Bold,
        7 => FontWeight::UltraBold,
        _ => FontWeight::Black,
    }
}

fn resolved_color_from_argb(argb: jint) -> ResolvedColor {
    let a = ((argb as u32) >> 24) as u8;
    let r = ((argb as u32) >> 16) as u8;
    let g = ((argb as u32) >> 8) as u8;
    let b = (argb as u32) as u8;

    let srgb = waterui_graphics::color::Srgb::new_u8(r, g, b);
    let mut resolved = ResolvedColor::from_srgb(srgb);
    resolved.opacity = a as f32 / 255.0;
    resolved
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_createReactiveColorSchemeState<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    scheme: jint,
) -> jlong {
    let scheme = if scheme == 0 {
        waterui::theme::ColorScheme::Light
    } else {
        waterui::theme::ColorScheme::Dark
    };
    let state = ReactiveColorSchemeState {
        binding: waterui::reactive::binding(scheme),
    };
    Box::into_raw(Box::new(state)) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_reactiveColorSchemeStateToComputed<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jlong {
    if state_ptr == 0 {
        return 0;
    }
    let state = unsafe { &*(state_ptr as *const ReactiveColorSchemeState) };
    let computed = state.binding.computed();
    computed.into_ffi() as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_reactiveColorSchemeStateSet<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    scheme: jint,
) {
    if state_ptr == 0 {
        return;
    }
    let state = unsafe { &*(state_ptr as *const ReactiveColorSchemeState) };
    let scheme = if scheme == 0 {
        waterui::theme::ColorScheme::Light
    } else {
        waterui::theme::ColorScheme::Dark
    };
    state.binding.set(scheme);
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_computedColorSchemeConstant<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    scheme: jint,
) -> jlong {
    let scheme = if scheme == 0 {
        crate::theme::WuiColorScheme::Light
    } else {
        crate::theme::WuiColorScheme::Dark
    };
    crate::theme::waterui_computed_color_scheme_constant(scheme) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_createReactiveColorState<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    argb: jint,
) -> jlong {
    let state = ReactiveColorState {
        binding: waterui::reactive::binding(resolved_color_from_argb(argb)),
    };
    Box::into_raw(Box::new(state)) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_reactiveColorStateToComputed<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jlong {
    if state_ptr == 0 {
        return 0;
    }
    let state = unsafe { &*(state_ptr as *const ReactiveColorState) };
    let computed = state.binding.computed();
    computed.into_ffi() as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_reactiveColorStateSet<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    argb: jint,
) {
    if state_ptr == 0 {
        return;
    }
    let state = unsafe { &*(state_ptr as *const ReactiveColorState) };
    state.binding.set(resolved_color_from_argb(argb));
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_createReactiveFontState<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    size: jfloat,
    weight: jint,
) -> jlong {
    let font = ResolvedFont::new(size, font_weight_from_ordinal(weight));
    let state = ReactiveFontState {
        binding: waterui::reactive::binding(font),
    };
    Box::into_raw(Box::new(state)) as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_reactiveFontStateToComputed<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jlong {
    if state_ptr == 0 {
        return 0;
    }
    let state = unsafe { &*(state_ptr as *const ReactiveFontState) };
    let computed = state.binding.computed();
    computed.into_ffi() as jlong
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_reactiveFontStateSet<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    size: jfloat,
    weight: jint,
) {
    if state_ptr == 0 {
        return;
    }
    let state = unsafe { &*(state_ptr as *const ReactiveFontState) };
    state
        .binding
        .set(ResolvedFont::new(size, font_weight_from_ordinal(weight)));
}

// ============================================================================
// WebView Functions (drop function is generated by opaque! macro)
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_webviewNativeHandle<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    webview_ptr: jlong,
) -> jlong {
    if webview_ptr == 0 {
        return 0;
    }
    unsafe {
        crate::components::webview::waterui_webview_native_handle(
            webview_ptr as *mut crate::components::webview::WuiWebView,
        ) as jlong
    }
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_webviewNativeView<'local>(
    mut _env: JNIEnv<'local>,
    _class: JClass<'local>,
    handle_ptr: jlong,
) -> jobject {
    crate::jni::webview_bridge::webview_native_view(&mut _env, handle_ptr)
}

// ============================================================================
// GpuSurface Functions
// ============================================================================

#[cfg(target_os = "android")]
struct JniGpuSurfaceState {
    state: *mut crate::components::gpu_surface::WuiGpuSurfaceState,
    window: AndroidNativeWindow,
}

#[cfg(target_os = "android")]
struct JniAppliedFilterState {
    state: *mut crate::components::applied_filter::WuiAppliedFilterState,
    window: AndroidNativeWindow,
}

#[cfg(target_os = "android")]
struct JniViewEffectState {
    state: *mut crate::components::view_effect::WuiViewEffectState,
    window: AndroidNativeWindow,
}

#[cfg(target_os = "android")]
unsafe extern "C" fn drop_hardware_buffer_ref(data: *mut c_void) {
    if data.is_null() {
        return;
    }
    let _ = unsafe { Box::from_raw(data as *mut ndk::hardware_buffer::HardwareBufferRef) };
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceInit<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _renderer_ptr: jlong,
    _surface: JObject<'local>,
    _width: jint,
    _height: jint,
) -> jlong {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceInit<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    renderer_ptr: jlong,
    surface: JObject<'local>,
    width: jint,
    height: jint,
) -> jlong {
    // Note: Kotlin calls this init entry point as `gpuSurfaceInit(rendererPtr, surface, w, h)`
    // where `rendererPtr` is the boxed `GpuSurface` pointer (not a WuiGpuSurface struct).
    // Reconstruct a temporary WuiGpuSurface for the C-FFI init function.
    let env_ptr = env.get_native_interface();
    let Some(window) = (unsafe { AndroidNativeWindow::from_surface(env_ptr, surface.as_raw()) })
    else {
        return 0;
    };

    let mut wui_surface = crate::components::gpu_surface::WuiGpuSurface {
        surface: renderer_ptr as *mut c_void,
    };

    let state = unsafe {
        crate::components::gpu_surface::waterui_gpu_surface_init(
            &mut wui_surface,
            window.as_void_ptr(),
            width as u32,
            height as u32,
        )
    };
    if state.is_null() {
        return 0;
    }

    let wrapper = Box::new(JniGpuSurfaceState { state, window });
    Box::into_raw(wrapper) as jlong
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceSetInput<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
    _has_position: jboolean,
    _x: jfloat,
    _y: jfloat,
    _has_hit: jboolean,
    _hit_x: jfloat,
    _hit_y: jfloat,
    _gesture_active: jboolean,
    _pinch_scale: jfloat,
    _has_pinch_center: jboolean,
    _pinch_center_x: jfloat,
    _pinch_center_y: jfloat,
    _pan_offset_x: jfloat,
    _pan_offset_y: jfloat,
    _double_tap: jboolean,
) {
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceRender<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    width: jint,
    height: jint,
) -> jlong {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniGpuSurfaceState) };
    let result = unsafe {
        crate::components::gpu_surface::waterui_gpu_surface_render(
            wrapper.state,
            width as u32,
            height as u32,
        )
    };
    let mut packed: u64 = 0;
    if result.ok {
        packed |= 1;
    }
    if result.needs_redraw {
        packed |= 1 << 1;
    }
    packed as jlong
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceNeedsRedraw<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) -> jboolean {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceNeedsRedraw<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jboolean {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniGpuSurfaceState) };
    let needs_redraw =
        unsafe { crate::components::gpu_surface::waterui_gpu_surface_needs_redraw(wrapper.state) };
    if needs_redraw { 1 } else { 0 }
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceRequiresRedrawPoll<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) -> jboolean {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceRequiresRedrawPoll<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jboolean {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniGpuSurfaceState) };
    let requires_poll = unsafe {
        crate::components::gpu_surface::waterui_gpu_surface_requires_redraw_poll(wrapper.state)
    };
    if requires_poll { 1 } else { 0 }
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
#[allow(clippy::too_many_arguments)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceSetInput<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    has_position: jboolean,
    x: jfloat,
    y: jfloat,
    has_hit: jboolean,
    hit_x: jfloat,
    hit_y: jfloat,
    gesture_active: jboolean,
    pinch_scale: jfloat,
    has_pinch_center: jboolean,
    pinch_center_x: jfloat,
    pinch_center_y: jfloat,
    pan_offset_x: jfloat,
    pan_offset_y: jfloat,
    double_tap: jboolean,
) {
    if state_ptr == 0 {
        return;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniGpuSurfaceState) };

    let input = crate::components::gpu_surface::WuiGpuSurfaceInput {
        pointer: crate::components::gpu_surface::WuiPointerState {
            has_position: has_position != 0,
            x,
            y,
            has_hit: has_hit != 0,
            hit_x,
            hit_y,
        },
        gesture: crate::components::gpu_surface::WuiGestureState {
            active: gesture_active != 0,
            pinch_scale,
            has_pinch_center: has_pinch_center != 0,
            pinch_center_x,
            pinch_center_y,
            pan_offset_x,
            pan_offset_y,
            double_tap: double_tap != 0,
        },
    };

    unsafe {
        crate::components::gpu_surface::waterui_gpu_surface_set_input(wrapper.state, input);
    }
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceDrop<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) {
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_gpuSurfaceDrop<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) {
    if state_ptr == 0 {
        return;
    }
    let wrapper = unsafe { Box::from_raw(state_ptr as *mut JniGpuSurfaceState) };
    unsafe {
        crate::components::gpu_surface::waterui_gpu_surface_drop(wrapper.state);
    }
    drop(wrapper);
}

// ============================================================================
// AppliedFilter Functions
// ============================================================================

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterInit<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _content_ptr: jlong,
    _filter_ptr: jlong,
    _surface: JObject<'local>,
    _width: jint,
    _height: jint,
) -> jlong {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterInit<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    content_ptr: jlong,
    filter_ptr: jlong,
    surface: JObject<'local>,
    width: jint,
    height: jint,
) -> jlong {
    let env_ptr = env.get_native_interface();
    let Some(window) = (unsafe { AndroidNativeWindow::from_surface(env_ptr, surface.as_raw()) })
    else {
        return 0;
    };

    let mut wui_filter = crate::components::applied_filter::WuiAppliedFilter {
        content: content_ptr as *mut crate::WuiAnyView,
        filter: filter_ptr as *mut c_void,
    };

    let state = unsafe {
        crate::components::applied_filter::waterui_applied_filter_init(
            &mut wui_filter,
            window.as_void_ptr(),
            width as u32,
            height as u32,
        )
    };
    if state.is_null() {
        return 0;
    }

    let wrapper = Box::new(JniAppliedFilterState { state, window });
    Box::into_raw(wrapper) as jlong
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterSetup<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
    _callback: JObject<'local>,
) {
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterSetup<'local>(
    env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    callback: JObject<'local>,
) {
    if state_ptr == 0 {
        return;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniAppliedFilterState) };
    let runnable = env
        .new_global_ref(callback)
        .expect("AppliedFilterSetup: global ref");

    unsafe extern "C" fn run_callback(data: *mut c_void) {
        let runnable = unsafe { Box::from_raw(data as *mut GlobalRef) };
        crate::jni::with_jni_env(|env| {
            env.call_method(&*runnable, "run", "()V", &[])
                .expect("AppliedFilterSetup.run_callback: Java runnable run() failed");
        });
    }

    let boxed = Box::new(runnable);
    let user_data = Box::into_raw(boxed) as *mut c_void;

    unsafe {
        crate::components::applied_filter::waterui_applied_filter_setup(
            wrapper.state,
            run_callback,
            user_data,
        );
    }
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterSyncTargets<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) -> jboolean {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterSyncTargets<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jboolean {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniAppliedFilterState) };
    let ok = unsafe {
        crate::components::applied_filter::waterui_applied_filter_sync_targets(wrapper.state)
    };
    if ok { 1 } else { 0 }
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterPollRedraw<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) -> jboolean {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterPollRedraw<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jboolean {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniAppliedFilterState) };
    let should_redraw = unsafe {
        crate::components::applied_filter::waterui_applied_filter_poll_redraw(wrapper.state)
    };
    if should_redraw { 1 } else { 0 }
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterSetInputAHardwareBuffer<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
    _hardware_buffer: JObject<'local>,
    _width: jint,
    _height: jint,
) -> jboolean {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterSetInputAHardwareBuffer<
    'local,
>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    hardware_buffer: JObject<'local>,
    width: jint,
    height: jint,
) -> jboolean {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniAppliedFilterState) };

    let env_ptr = env.get_native_interface();
    let hb = unsafe { HardwareBuffer::from_jni(env_ptr, hardware_buffer.as_raw()) };
    let hb_ref = hb.acquire();
    let ahb_ptr = hb_ref.as_ptr().cast::<c_void>();
    let drop_data = Box::into_raw(Box::new(hb_ref)) as *mut c_void;

    let ok = unsafe {
        crate::components::applied_filter::waterui_applied_filter_set_input_ahardwarebuffer(
            wrapper.state,
            ahb_ptr,
            drop_hardware_buffer_ref,
            drop_data,
            width as u32,
            height as u32,
        )
    };

    if !ok {
        unsafe { drop_hardware_buffer_ref(drop_data) };
    }

    if ok { 1 } else { 0 }
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterRender<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
    _width: jint,
    _height: jint,
) -> jobject {
    core::ptr::null_mut()
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterRender<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    width: jint,
    height: jint,
) -> jobject {
    if state_ptr == 0 {
        return core::ptr::null_mut();
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniAppliedFilterState) };
    let result = unsafe {
        crate::components::applied_filter::waterui_applied_filter_render(
            wrapper.state,
            width as u32,
            height as u32,
        )
    };

    let class = env
        .find_class("dev/waterui/android/runtime/AppliedFilterRenderResultStruct")
        .expect("AppliedFilterRenderResultStruct class not found");
    env.new_object(
        &class,
        "(ZZ)V",
        &[
            JValue::Bool(if result.success { 1 } else { 0 }),
            JValue::Bool(if result.needs_redraw { 1 } else { 0 }),
        ],
    )
    .expect("Failed to create AppliedFilterRenderResultStruct")
    .into_raw()
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterDrop<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) {
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_appliedFilterDrop<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) {
    if state_ptr == 0 {
        return;
    }
    let wrapper = unsafe { Box::from_raw(state_ptr as *mut JniAppliedFilterState) };
    unsafe {
        crate::components::applied_filter::waterui_applied_filter_drop(wrapper.state);
    }
    drop(wrapper);
}

// ============================================================================
// ViewEffect Functions
// ============================================================================

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectInit<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _effect_ptr: jlong,
    _surface: JObject<'local>,
    _width: jint,
    _height: jint,
) -> jlong {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectInit<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    effect_ptr: jlong,
    surface: JObject<'local>,
    width: jint,
    height: jint,
) -> jlong {
    let env_ptr = env.get_native_interface();
    let Some(window) = (unsafe { AndroidNativeWindow::from_surface(env_ptr, surface.as_raw()) })
    else {
        return 0;
    };

    let state = unsafe {
        crate::components::view_effect::waterui_view_effect_init(
            effect_ptr as *mut crate::components::view_effect::WuiViewEffect,
            window.as_void_ptr(),
            width as u32,
            height as u32,
        )
    };
    if state.is_null() {
        return 0;
    }

    let wrapper = Box::new(JniViewEffectState { state, window });
    Box::into_raw(wrapper) as jlong
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectRender<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) -> jobject {
    core::ptr::null_mut()
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectRender<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) -> jobject {
    if state_ptr == 0 {
        return core::ptr::null_mut();
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniViewEffectState) };
    let result =
        unsafe { crate::components::view_effect::waterui_view_effect_render(wrapper.state) };

    let class = env
        .find_class("dev/waterui/android/runtime/ViewEffectRenderResultStruct")
        .expect("ViewEffectRenderResultStruct class not found");
    env.new_object(
        &class,
        "(ZZ)V",
        &[
            JValue::Bool(if result.success { 1 } else { 0 }),
            JValue::Bool(if result.needs_redraw { 1 } else { 0 }),
        ],
    )
    .expect("Failed to create ViewEffectRenderResultStruct")
    .into_raw()
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectDrop<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
) {
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectDrop<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
) {
    if state_ptr == 0 {
        return;
    }
    let wrapper = unsafe { Box::from_raw(state_ptr as *mut JniViewEffectState) };
    unsafe {
        crate::components::view_effect::waterui_view_effect_drop(wrapper.state);
    }
    drop(wrapper);
}

#[cfg(not(target_os = "android"))]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectSetInputAHardwareBuffer<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    _state_ptr: jlong,
    _hardware_buffer: JObject<'local>,
    _width: jint,
    _height: jint,
) -> jboolean {
    0
}

#[cfg(target_os = "android")]
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_viewEffectSetInputAHardwareBuffer<
    'local,
>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    state_ptr: jlong,
    hardware_buffer: JObject<'local>,
    width: jint,
    height: jint,
) -> jboolean {
    if state_ptr == 0 {
        return 0;
    }
    let wrapper = unsafe { &mut *(state_ptr as *mut JniViewEffectState) };

    let env_ptr = env.get_native_interface();
    let hb = unsafe { HardwareBuffer::from_jni(env_ptr, hardware_buffer.as_raw()) };
    let hb_ref = hb.acquire();
    let ahb_ptr = hb_ref.as_ptr().cast::<c_void>();
    let drop_data = Box::into_raw(Box::new(hb_ref)) as *mut c_void;

    let ok = unsafe {
        crate::components::view_effect::waterui_view_effect_set_input_ahardwarebuffer(
            wrapper.state,
            ahb_ptr,
            drop_hardware_buffer_ref,
            drop_data,
            width as u32,
            height as u32,
        )
    };

    if !ok {
        unsafe { drop_hardware_buffer_ref(drop_data) };
    }

    if ok { 1 } else { 0 }
}

// ============================================================================
// Drag and Drop Functions
// ============================================================================
// Note: metadataDraggableId, metadataDropDestinationId, forceAsMetadataDraggable,
// and forceAsMetadataDropDestination are generated by ffi_metadata! macro

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_draggableGetData<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    draggable_ptr: jlong,
) -> jobject {
    let data = unsafe {
        crate::drag_drop::waterui_draggable_get_data(
            draggable_ptr as *const crate::drag_drop::WuiDraggable,
        )
    };

    let tag_class = env
        .find_class("dev/waterui/android/components/DragDataTag")
        .expect("DragDataTag class not found");
    let tag_field = match data.tag {
        crate::drag_drop::WuiDragDataTag::Text => "TEXT",
        crate::drag_drop::WuiDragDataTag::Url => "URL",
    };
    let tag_obj = env
        .get_static_field(
            &tag_class,
            tag_field,
            "Ldev/waterui/android/components/DragDataTag;",
        )
        .expect("DragDataTag.<FIELD>")
        .l()
        .expect("DragDataTag field is object");

    let value: waterui::Str = unsafe { data.value.into_rust() };
    let jvalue = env
        .new_string(value.as_str())
        .expect("Failed to create DragDataStruct.value string");

    let class = env
        .find_class("dev/waterui/android/components/DragDataStruct")
        .expect("DragDataStruct class not found");
    env.new_object(
        &class,
        "(Ldev/waterui/android/components/DragDataTag;Ljava/lang/String;)V",
        &[JValue::Object(&tag_obj), JValue::Object(&jvalue)],
    )
    .expect("Failed to create DragDataStruct")
    .into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropDraggable<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    draggable_ptr: jlong,
) {
    unsafe {
        crate::drag_drop::waterui_drop_draggable(
            draggable_ptr as *mut crate::drag_drop::WuiDraggable,
        )
    };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropDropDestination<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    drop_dest_ptr: jlong,
) {
    unsafe {
        crate::drag_drop::waterui_drop_drop_destination(
            drop_dest_ptr as *mut crate::drag_drop::WuiDropDestination,
        )
    };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callDropHandler<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    drop_dest_ptr: jlong,
    env_ptr: jlong,
    data_tag: jint,
    data_value: JString<'local>,
) {
    let drop_dest = drop_dest_ptr as *const crate::drag_drop::WuiDropDestination;
    let wui_env = env_ptr as *const crate::WuiEnv;
    let value: String = env
        .get_string(&data_value)
        .expect("WatcherJni.callDropHandler: failed to read data_value")
        .into();
    let tag = if data_tag == 0 {
        crate::drag_drop::WuiDragDataTag::Text
    } else {
        crate::drag_drop::WuiDragDataTag::Url
    };
    let c_str = alloc::ffi::CString::new(value)
        .expect("WatcherJni.callDropHandler: data_value contains interior NUL");
    unsafe { crate::drag_drop::waterui_call_drop_handler(drop_dest, wui_env, tag, c_str.as_ptr()) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callDropEnterHandler<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    drop_dest_ptr: jlong,
    env_ptr: jlong,
) {
    let drop_dest = drop_dest_ptr as *const crate::drag_drop::WuiDropDestination;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::drag_drop::waterui_call_drop_enter_handler(drop_dest, wui_env) };
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_callDropExitHandler<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    drop_dest_ptr: jlong,
    env_ptr: jlong,
) {
    let drop_dest = drop_dest_ptr as *const crate::drag_drop::WuiDropDestination;
    let wui_env = env_ptr as *const crate::WuiEnv;
    unsafe { crate::drag_drop::waterui_call_drop_exit_handler(drop_dest, wui_env) };
}
