//! JNI bindings for WaterUI Android backend.
//!
//! This module provides pure Rust JNI bindings using jni-rs, replacing the
//! previous C++ JNI layer (waterui_jni.cpp).
//!
//! The module is only compiled when the `android-jni` feature is enabled.

extern crate std;

pub mod android_runtime;
pub mod components;
pub mod convert;
pub mod ffi_bridge;
pub mod navigation;
pub mod reactive;
pub mod webview_bridge;

pub use convert::JniPrimitive;

// Re-export jni types needed by macros
pub use jni;
pub use jni::objects::{GlobalRef, JClass, JObject, JValue};
pub use jni::sys::{JNI_VERSION_1_6, jboolean, jdouble, jfloat, jint, jlong, jobject};
pub use jni::{JNIEnv, JavaVM};

/// Returns the JNI version supported by this module.
///
/// # Safety
///
/// `vm` must be the live VM pointer supplied to `JNI_OnLoad`.
pub unsafe fn init(_vm: *mut jni::sys::JavaVM) -> jint {
    tracing::debug!("WaterUI JNI module initialized");
    JNI_VERSION_1_6
}
/// Convert a WuiTypeId to a Java TypeIdStruct object.
pub fn type_id_to_java<'local>(
    env: &mut JNIEnv<'local>,
    type_id: crate::WuiTypeId,
) -> JObject<'local> {
    // TypeIdStruct is (low, high) to match Kotlin WuiTypeId(low, high).
    let low = type_id.low as jlong;
    let high = type_id.high as jlong;
    env.new_object(
        "dev/waterui/android/runtime/TypeIdStruct",
        "(JJ)V",
        &[JValue::Long(low), JValue::Long(high)],
    )
    .expect("Failed to create TypeIdStruct")
}

/// Extracts (data_ptr, call_ptr, drop_ptr) from a Java WatcherStruct object.
///
/// This function is used by the generated JNI watch functions in `ffi_computed!`
/// and `ffi_binding!` macros to extract the watcher callback pointers.
pub fn extract_watcher_struct(env: &mut JNIEnv, watcher: &JObject) -> (jlong, jlong, jlong) {
    let data_ptr = env
        .get_field(watcher, "dataPtr", "J")
        .expect("Failed to get dataPtr")
        .j()
        .expect("dataPtr is not a long");
    let call_ptr = env
        .get_field(watcher, "callPtr", "J")
        .expect("Failed to get callPtr")
        .j()
        .expect("callPtr is not a long");
    let drop_ptr = env
        .get_field(watcher, "dropPtr", "J")
        .expect("Failed to get dropPtr")
        .j()
        .expect("dropPtr is not a long");
    (data_ptr, call_ptr, drop_ptr)
}

// Note: JNI_OnLoad is generated by the export!() macro in lib.rs
// to ensure all initialization happens in the correct order.
