//! JNI navigation functions for WaterUI Android.
//!
//! This module provides JNI functions for navigation controllers that are NOT
//! generated by macros. All type IDs and forceAs functions are auto-generated
//! by the `ffi_view!` and `ffi_metadata!` macros in their respective modules.

extern crate alloc;
extern crate std;

use alloc::boxed::Box;
use jni::JNIEnv;
use jni::objects::{GlobalRef, JClass, JObject, JValue};
use jni::sys::{jboolean, jint, jlong, jobject};
use std::sync::Arc;

/// Data for the JNI navigation controller callback.
struct JniNavigationCallbackData {
    jvm: Arc<jni::JavaVM>,
    callback: GlobalRef,
}

impl JniNavigationCallbackData {
    fn with_env<R>(&self, f: impl FnOnce(&mut JNIEnv) -> R) -> R {
        let mut env = self
            .jvm
            .attach_current_thread()
            .expect("navigation callback failed to attach its JVM thread");
        f(&mut env)
    }
}

/// C-compatible push callback that calls into Java.
unsafe extern "C" fn jni_navigation_push(
    data: *mut (),
    nav_view: crate::components::navigation::WuiNavigationView,
) {
    let data = unsafe { &*(data as *const JniNavigationCallbackData) };
    data.with_env(|env| {
        // Convert WuiNavigationView to Java object
        let java_nav_view = crate::jni::convert::struct_to_java(env, &nav_view);
        env.call_method(
            data.callback.as_obj(),
            "onPush",
            "(Ldev/waterui/android/runtime/NavigationViewStruct;)V",
            &[JValue::Object(&java_nav_view)],
        )
        .expect("jni_navigation_push: failed to call callback.onPush(NavigationViewStruct)");
    });
}

/// C-compatible pop callback.
unsafe extern "C" fn jni_navigation_pop(data: *mut ()) {
    let data = unsafe { &*(data as *const JniNavigationCallbackData) };
    data.with_env(|env| {
        env.call_method(data.callback.as_obj(), "onPop", "()V", &[])
            .expect("jni_navigation_pop: failed to call callback.onPop()");
    });
}

/// C-compatible drop callback to clean up the JNI data.
unsafe extern "C" fn jni_navigation_drop(data: *mut ()) {
    let _ = unsafe { Box::from_raw(data as *mut JniNavigationCallbackData) };
}

// ============================================================================
// Navigation Controller Functions
// ============================================================================

/// Installs a navigation controller with a Java callback into the environment.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_envInstallNavigationController<
    'local,
>(
    env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
    callback: JObject<'local>,
) {
    let global_callback = env
        .new_global_ref(callback)
        .expect("Failed to create global ref for navigation callback");

    let data = Box::new(JniNavigationCallbackData {
        jvm: Arc::new(
            env.get_java_vm()
                .expect("navigation controller failed to access JavaVM"),
        ),
        callback: global_callback,
    });
    let data_ptr = Box::into_raw(data) as *mut ();

    unsafe {
        crate::components::navigation::waterui_env_install_navigation_controller(
            env_ptr as *mut crate::WuiEnv,
            data_ptr,
            jni_navigation_push,
            jni_navigation_pop,
            jni_navigation_drop,
        )
    }
}

/// Checks if the environment has a navigation controller installed.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_envHasNavigationController<
    'local,
>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    env_ptr: jlong,
) -> jboolean {
    let wui_env = env_ptr as *const crate::WuiEnv;
    if unsafe { crate::components::navigation::waterui_env_has_navigation_controller(wui_env) } {
        1
    } else {
        0
    }
}

// ============================================================================
// Tab Content Function
// ============================================================================

/// Extracts the NavigationView content from a tab.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_tabContent<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    content_ptr: jlong,
    env_ptr: jlong,
) -> jobject {
    use crate::components::navigation::WuiTabContent;

    let content = content_ptr as *mut WuiTabContent;
    let wui_env = env_ptr as *const crate::WuiEnv;
    let nav_view = unsafe { crate::components::navigation::waterui_tab_content(content, wui_env) };
    crate::jni::convert::struct_to_java(&mut env, &nav_view).into_raw()
}

/// Resolves split detail content from a selected identifier.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_splitNavigationDetailContent<
    'local,
>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    detail_ptr: jlong,
    selected_id: jint,
    env_ptr: jlong,
) -> jobject {
    use crate::components::navigation::WuiNavigationSplitDetail;

    let detail = detail_ptr as *mut WuiNavigationSplitDetail;
    let wui_env = env_ptr as *const crate::WuiEnv;
    let nav_view = unsafe {
        crate::components::navigation::waterui_split_navigation_detail_content(
            detail,
            crate::id::WuiId { inner: selected_id },
            wui_env,
        )
    };
    crate::jni::convert::struct_to_java(&mut env, &nav_view).into_raw()
}
