//! JNI reactive bindings for Binding and Computed types.
//!
//! Most functions are auto-generated by macros in `reactive.rs`:
//! - `ffi_binding!` / `ffi_computed!` generate drop and watch functions
//! - `jni_binding_primitive!` / `jni_computed_primitive!` generate read/set for primitives
//!
//! This module contains:
//! - Complex type read/set (Str, Color, Date, etc.) that need custom JNI conversion
//! - Watcher creation functions with type-specific call trampolines
//! - Special aliases (WindowState uses i32 but has separate JNI name)

extern crate alloc;
extern crate std;

use alloc::boxed::Box;
use alloc::vec::Vec;

use jni::JNIEnv;
use jni::objects::{JByteArray, JClass, JObject, JObjectArray, JString, JValue};
use jni::sys::{jint, jlong, jobject, jobjectArray, jsize};

use crate::reactive::{WuiBinding, WuiComputed, WuiWatcherGuard};

#[inline]
fn require_jlong_ptr<T>(ptr: jlong, function: &str, pointer_name: &str) -> *mut T {
    let _ = (function, pointer_name);
    ptr as *mut T
}

// ============================================================================
// Helper Functions for Complex Type Conversion
// ============================================================================

/// Create a ResolvedColorStruct Java object from Rust values.
fn create_resolved_color_struct<'local>(
    env: &mut JNIEnv<'local>,
    red: f32,
    green: f32,
    blue: f32,
    opacity: f32,
    headroom: f32,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    unsafe {
        env.new_object_unchecked(
            &classes.resolved_color_struct_class,
            jni::objects::JMethodID::from_raw(classes.resolved_color_struct_ctor),
            &[
                JValue::Float(red).as_jni(),
                JValue::Float(green).as_jni(),
                JValue::Float(blue).as_jni(),
                JValue::Float(opacity).as_jni(),
                JValue::Float(headroom).as_jni(),
            ],
        )
        .expect("Failed to create ResolvedColorStruct")
    }
}

/// Create a ResolvedFontStruct Java object from Rust values.
fn create_resolved_font_struct<'local>(
    env: &mut JNIEnv<'local>,
    size: f32,
    weight: i32,
    family: &str,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    let family = env
        .new_string(family)
        .expect("Failed to create font family string");
    unsafe {
        env.new_object_unchecked(
            &classes.resolved_font_struct_class,
            jni::objects::JMethodID::from_raw(classes.resolved_font_struct_ctor),
            &[
                JValue::Float(size).as_jni(),
                JValue::Int(weight).as_jni(),
                JValue::Object(&family).as_jni(),
            ],
        )
        .expect("Failed to create ResolvedFontStruct")
    }
}

/// Create a RegionStruct Java object from Rust values.
fn create_region_struct<'local>(
    env: &mut JNIEnv<'local>,
    center_lat: f64,
    center_lon: f64,
    lat_delta: f64,
    lon_delta: f64,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    unsafe {
        env.new_object_unchecked(
            &classes.region_struct_class,
            jni::objects::JMethodID::from_raw(classes.region_struct_ctor),
            &[
                JValue::Double(center_lat).as_jni(),
                JValue::Double(center_lon).as_jni(),
                JValue::Double(lat_delta).as_jni(),
                JValue::Double(lon_delta).as_jni(),
            ],
        )
        .expect("Failed to create RegionStruct")
    }
}

/// Create an AnnotationStruct Java object from Rust values.
fn create_annotation_struct<'local>(
    env: &mut JNIEnv<'local>,
    latitude: f64,
    longitude: f64,
    title: &str,
    subtitle: &str,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    let title_str = env
        .new_string(title)
        .expect("Failed to create title string");
    let subtitle_str = env
        .new_string(subtitle)
        .expect("Failed to create subtitle string");
    unsafe {
        env.new_object_unchecked(
            &classes.annotation_struct_class,
            jni::objects::JMethodID::from_raw(classes.annotation_struct_ctor),
            &[
                JValue::Double(latitude).as_jni(),
                JValue::Double(longitude).as_jni(),
                JValue::Object(&title_str).as_jni(),
                JValue::Object(&subtitle_str).as_jni(),
            ],
        )
        .expect("Failed to create AnnotationStruct")
    }
}

/// Create a VideoStruct Java object from Rust values.
fn create_video_struct<'local>(env: &mut JNIEnv<'local>, url: &str) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    let url_str = env.new_string(url).expect("Failed to create URL string");
    unsafe {
        env.new_object_unchecked(
            &classes.video_struct_class,
            jni::objects::JMethodID::from_raw(classes.video_struct_ctor),
            &[JValue::Object(&url_str).as_jni()],
        )
        .expect("Failed to create VideoStruct")
    }
}

/// Create a LivePhotoSourceStruct Java object from Rust values.
fn create_live_photo_source_struct<'local>(
    env: &mut JNIEnv<'local>,
    image: &str,
    video: &str,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    let image_str = env
        .new_string(image)
        .expect("Failed to create image string");
    let video_str = env
        .new_string(video)
        .expect("Failed to create video string");
    unsafe {
        env.new_object_unchecked(
            &classes.live_photo_source_struct_class,
            jni::objects::JMethodID::from_raw(classes.live_photo_source_struct_ctor),
            &[
                JValue::Object(&image_str).as_jni(),
                JValue::Object(&video_str).as_jni(),
            ],
        )
        .expect("Failed to create LivePhotoSourceStruct")
    }
}

/// Create a DateStruct Java object from Rust values.
fn create_date_struct<'local>(
    env: &mut JNIEnv<'local>,
    year: i32,
    month: i32,
    day: i32,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    unsafe {
        env.new_object_unchecked(
            &classes.date_struct_class,
            jni::objects::JMethodID::from_raw(classes.date_struct_ctor),
            &[
                JValue::Int(year).as_jni(),
                JValue::Int(month).as_jni(),
                JValue::Int(day).as_jni(),
            ],
        )
        .expect("Failed to create DateStruct")
    }
}

fn create_date_time_struct<'local>(
    env: &mut JNIEnv<'local>,
    year: i32,
    month: i32,
    day: i32,
    hour: i32,
    minute: i32,
    second: i32,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    unsafe {
        env.new_object_unchecked(
            &classes.date_time_struct_class,
            jni::objects::JMethodID::from_raw(classes.date_time_struct_ctor),
            &[
                JValue::Int(year).as_jni(),
                JValue::Int(month).as_jni(),
                JValue::Int(day).as_jni(),
                JValue::Int(hour).as_jni(),
                JValue::Int(minute).as_jni(),
                JValue::Int(second).as_jni(),
            ],
        )
        .expect("Failed to create DateTimeStruct")
    }
}

// ============================================================================
// String-based Binding Macros (Str, Secure use byte array conversion)
// ============================================================================

/// Helper for reading a Str binding as byte array
fn read_binding_str_to_bytes(env: &mut JNIEnv, binding_ptr: jlong) -> jobject {
    use nami::Signal;
    let binding = unsafe { &*(binding_ptr as *const WuiBinding<waterui::Str>) };
    let s: waterui::Str = binding.get();
    let bytes = s.as_bytes();
    let byte_array = env
        .new_byte_array(bytes.len() as i32)
        .expect("Failed to create byte array");
    env.set_byte_array_region(&byte_array, 0, unsafe {
        core::slice::from_raw_parts(bytes.as_ptr() as *const i8, bytes.len())
    })
    .expect("Failed to set byte array region");
    byte_array.into_raw()
}

/// Helper for setting a Str binding from byte array
fn set_binding_str_from_bytes(env: &mut JNIEnv, binding_ptr: jlong, bytes: &JByteArray) {
    let binding = unsafe { &*(binding_ptr as *const WuiBinding<waterui::Str>) };
    let len = env
        .get_array_length(bytes)
        .expect("set_binding_str_from_bytes: failed to read byte array length")
        as usize;
    let mut buf = alloc::vec![0i8; len];
    env.get_byte_array_region(bytes, 0, &mut buf)
        .expect("set_binding_str_from_bytes: failed to read byte array content");
    let bytes: Vec<u8> = buf.into_iter().map(|b| b as u8).collect();
    let s = waterui::Str::from_utf8(bytes)
        .expect("set_binding_str_from_bytes: input byte array is not valid UTF-8");
    binding.set(s);
}

/// Generates JNI read/set functions for Str-based binding types (using byte array).
macro_rules! jni_binding_str {
    ($name:tt) => {
        pastey::paste! {
            #[unsafe(no_mangle)]
            pub extern "system" fn [<Java_dev_waterui_android_ffi_WatcherJni_readBinding $name:camel>]<'local>(
                mut env: JNIEnv<'local>,
                _class: JClass<'local>,
                binding_ptr: jlong,
            ) -> jobject {
                read_binding_str_to_bytes(&mut env, binding_ptr)
            }

            #[unsafe(no_mangle)]
            pub extern "system" fn [<Java_dev_waterui_android_ffi_WatcherJni_setBinding $name:camel>]<'local>(
                mut env: JNIEnv<'local>,
                _class: JClass<'local>,
                binding_ptr: jlong,
                bytes: JByteArray<'local>,
            ) {
                set_binding_str_from_bytes(&mut env, binding_ptr, &bytes);
            }
        }
    };
}

// Generate Str and Secure binding functions
jni_binding_str!(str);
jni_binding_str!(secure);

fn styled_str_from_java(env: &mut JNIEnv, styled: &JObject) -> waterui_text::styled::StyledStr {
    use crate::IntoRust;
    use crate::color::WuiColor;
    use crate::components::text::WuiFont;
    use waterui_text::styled::{Style, StyledStr};

    let chunks_obj = env
        .get_field(
            styled,
            "chunks",
            "[Ldev/waterui/android/runtime/StyledChunkStruct;",
        )
        .expect("StyledStrStruct.chunks field not found")
        .l()
        .expect("StyledStrStruct.chunks should be an object array");
    let chunks_array = JObjectArray::from(chunks_obj);

    let len = env
        .get_array_length(&chunks_array)
        .expect("Failed to read StyledStrStruct chunks length");

    let mut styled_str = StyledStr::empty();

    for index in 0..len {
        let chunk_obj = env
            .get_object_array_element(&chunks_array, index)
            .expect("Failed to read StyledChunkStruct from array");
        let text_obj = env
            .get_field(&chunk_obj, "text", "Ljava/lang/String;")
            .expect("StyledChunkStruct.text field not found")
            .l()
            .expect("StyledChunkStruct.text should be a java.lang.String");
        let text_jstr = JString::from(text_obj);
        let text = env
            .get_string(&text_jstr)
            .expect("Failed to read StyledChunkStruct.text")
            .to_string_lossy()
            .into_owned();

        let style_obj = env
            .get_field(
                &chunk_obj,
                "style",
                "Ldev/waterui/android/runtime/TextStyleStruct;",
            )
            .expect("StyledChunkStruct.style field not found")
            .l()
            .expect("StyledChunkStruct.style should be a TextStyleStruct");

        let font_ptr = env
            .get_field(&style_obj, "fontPtr", "J")
            .expect("TextStyleStruct.fontPtr field not found")
            .j()
            .expect("TextStyleStruct.fontPtr should be a long");
        let italic = env
            .get_field(&style_obj, "italic", "Z")
            .expect("TextStyleStruct.italic field not found")
            .z()
            .expect("TextStyleStruct.italic should be a boolean");
        let underline = env
            .get_field(&style_obj, "underline", "Z")
            .expect("TextStyleStruct.underline field not found")
            .z()
            .expect("TextStyleStruct.underline should be a boolean");
        let strikethrough = env
            .get_field(&style_obj, "strikethrough", "Z")
            .expect("TextStyleStruct.strikethrough field not found")
            .z()
            .expect("TextStyleStruct.strikethrough should be a boolean");
        let foreground_ptr = env
            .get_field(&style_obj, "foregroundPtr", "J")
            .expect("TextStyleStruct.foregroundPtr field not found")
            .j()
            .expect("TextStyleStruct.foregroundPtr should be a long");
        let background_ptr = env
            .get_field(&style_obj, "backgroundPtr", "J")
            .expect("TextStyleStruct.backgroundPtr field not found")
            .j()
            .expect("TextStyleStruct.backgroundPtr should be a long");

        let font = unsafe { (font_ptr as *mut WuiFont).into_rust() };

        let foreground = if foreground_ptr == 0 {
            None
        } else {
            Some(unsafe { (foreground_ptr as *mut WuiColor).into_rust() })
        };

        let background = if background_ptr == 0 {
            None
        } else if background_ptr == foreground_ptr && foreground.is_some() {
            foreground.clone()
        } else {
            Some(unsafe { (background_ptr as *mut WuiColor).into_rust() })
        };

        styled_str.push(
            waterui::Str::from(text),
            Style {
                font,
                italic,
                underline,
                strikethrough,
                foreground,
                background,
            },
        );
    }

    styled_str
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readBindingStyledStr<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
) -> jobject {
    use nami::Signal;
    use waterui_text::styled::StyledStr;

    let binding = unsafe {
        &*require_jlong_ptr::<WuiBinding<StyledStr>>(binding_ptr, "readBindingStyledStr", "binding")
    };
    let styled: StyledStr = binding.get();
    styled_str_to_java(&mut env, styled).into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_setBindingStyledStr<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
    styled: JObject<'local>,
) {
    use waterui_text::styled::StyledStr;

    let binding = unsafe {
        &*require_jlong_ptr::<WuiBinding<StyledStr>>(binding_ptr, "setBindingStyledStr", "binding")
    };
    let value = styled_str_from_java(&mut env, &styled);
    binding.set(value);
}

// Color read/set is generated by jni_binding_primitive! in color.rs

// WindowState read/set is generated by jni_binding_primitive! in window.rs

// --- Date Binding ---

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readBindingDate<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use nami::Signal;
    use waterui_form::picker::date::Date;

    let binding = unsafe {
        &*require_jlong_ptr::<WuiBinding<Date>>(binding_ptr, "readBindingDate", "binding")
    };
    let date: Date = binding.get();
    let ffi = date.into_ffi();

    create_date_struct(&mut env, ffi.year, ffi.month as i32, ffi.day as i32).into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_setBindingDate<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
    year: jint,
    month: jint,
    day: jint,
) {
    use crate::IntoRust;
    use crate::components::form::WuiDate;
    use waterui_form::picker::date::Date;

    let binding = unsafe {
        &*require_jlong_ptr::<WuiBinding<Date>>(binding_ptr, "setBindingDate", "binding")
    };
    let wui_date = WuiDate {
        year,
        month: month as u8,
        day: day as u8,
    };
    let date = unsafe { wui_date.into_rust() };
    binding.set(date);
}

// --- DateTime Binding ---

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readBindingDateTime<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use jiff::civil::DateTime;
    use nami::Signal;

    let binding = unsafe {
        &*require_jlong_ptr::<WuiBinding<DateTime>>(binding_ptr, "readBindingDateTime", "binding")
    };
    let date_time: DateTime = binding.get();
    let ffi = date_time.into_ffi();

    create_date_time_struct(
        &mut env,
        ffi.year,
        ffi.month as i32,
        ffi.day as i32,
        ffi.hour as i32,
        ffi.minute as i32,
        ffi.second as i32,
    )
    .into_raw()
}

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_setBindingDateTime<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
    year: jint,
    month: jint,
    day: jint,
    hour: jint,
    minute: jint,
    second: jint,
) {
    use crate::IntoRust;
    use crate::components::form::WuiDateTime;
    use jiff::civil::DateTime;

    let binding = unsafe {
        &*require_jlong_ptr::<WuiBinding<DateTime>>(binding_ptr, "setBindingDateTime", "binding")
    };
    let wui_date_time = WuiDateTime {
        year,
        month: month as u8,
        day: day as u8,
        hour: hour as u8,
        minute: minute as u8,
        second: second as u8,
    };
    let date_time = unsafe { wui_date_time.into_rust() };
    binding.set(date_time);
}

// ============================================================================
// Special Drop Functions (aliases that aren't covered by macros)
// ============================================================================

// Secure uses same type as Str but has separate JNI function
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropBindingSecure<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    binding_ptr: jlong,
) {
    unsafe {
        drop(Box::from_raw(
            require_jlong_ptr::<WuiBinding<waterui::Str>>(
                binding_ptr,
                "dropBindingSecure",
                "binding",
            ),
        ))
    };
}

// WindowState drop is generated by ffi_binding!(WindowState, WuiWindowState, window_state) in window.rs

// ============================================================================
// Complex Type Computed Read Functions
// Note: Primitives (bool, i32, f32, f64) are generated by jni_computed_primitive!
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedStr<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use waterui::Signal;
    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<waterui::Str>>(
            computed_ptr,
            "readComputedStr",
            "computed",
        )
    };
    let s: waterui::Str = computed.get();
    let jstring = env.new_string(s.as_str()).expect("Failed to create string");
    jstring.into_raw()
}

// readComputedColor is generated by jni_computed_primitive! in color.rs
// readComputedColorScheme and readComputedCursorStyle are generated by jni_computed_primitive! in reactive.rs

// ============================================================================
// Complex Computed Read Functions (proper implementations)
// ============================================================================

/// Read a ResolvedColor computed value and return Java ResolvedColorStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedResolvedColor<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use crate::color::WuiResolvedColor;
    use waterui::Signal;
    use waterui_graphics::color::ResolvedColor;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<ResolvedColor>>(
            computed_ptr,
            "readComputedResolvedColor",
            "computed",
        )
    };
    let resolved: ResolvedColor = computed.get();
    let ffi: WuiResolvedColor = resolved.into_ffi();

    create_resolved_color_struct(
        &mut env,
        ffi.red,
        ffi.green,
        ffi.blue,
        ffi.opacity,
        ffi.headroom,
    )
    .into_raw()
}

/// Read a ResolvedFont computed value and return Java ResolvedFontStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedResolvedFont<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui_text::font::ResolvedFont;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<ResolvedFont>>(
            computed_ptr,
            "readComputedResolvedFont",
            "computed",
        )
    };
    let resolved: ResolvedFont = computed.get();
    let ffi = resolved.into_ffi();

    // Convert weight enum to int (the enum repr(C) matches Java expectations)
    let weight_int = ffi.weight as i32;
    let family = unsafe { ffi.family.as_str() };
    create_resolved_font_struct(&mut env, ffi.size, weight_int, family).into_raw()
}

/// Read a StyledStr computed value and return Java StyledStrStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedStyledStr<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use waterui::Signal;
    use waterui_text::styled::StyledStr;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<StyledStr>>(
            computed_ptr,
            "readComputedStyledStr",
            "computed",
        )
    };
    let styled_str: StyledStr = computed.get();

    styled_str_to_java(&mut env, styled_str).into_raw()
}

/// Convert StyledStr to Java StyledStrStruct.
fn styled_str_to_java<'local>(
    env: &mut JNIEnv<'local>,
    styled_str: waterui_text::styled::StyledStr,
) -> JObject<'local> {
    use crate::IntoFFI;

    let ffi = styled_str.into_ffi();
    let chunks_slice = ffi.chunks.as_slice();

    let classes = crate::jni::java_classes();

    // Create array of chunks
    let chunk_array = env
        .new_object_array(
            chunks_slice.len() as jsize,
            &classes.styled_chunk_struct_class,
            JObject::null(),
        )
        .expect("Failed to create chunk array");

    for (i, chunk) in chunks_slice.iter().enumerate() {
        // Create TextStyleStruct
        let style = &chunk.style;
        let text_style = unsafe {
            env.new_object_unchecked(
                &classes.text_style_struct_class,
                jni::objects::JMethodID::from_raw(classes.text_style_struct_ctor),
                &[
                    JValue::Long(style.font as jlong).as_jni(),
                    JValue::Bool(if style.italic { 1 } else { 0 }).as_jni(),
                    JValue::Bool(if style.underline { 1 } else { 0 }).as_jni(),
                    JValue::Bool(if style.strikethrough { 1 } else { 0 }).as_jni(),
                    JValue::Long(style.foreground as jlong).as_jni(),
                    JValue::Long(style.background as jlong).as_jni(),
                ],
            )
            .expect("Failed to create TextStyleStruct")
        };

        // Get text from chunk
        let text_str = unsafe { chunk.text.as_str() };
        let text_jstring = env
            .new_string(text_str)
            .expect("Failed to create text string");

        // Create StyledChunkStruct
        let styled_chunk = unsafe {
            env.new_object_unchecked(
                &classes.styled_chunk_struct_class,
                jni::objects::JMethodID::from_raw(classes.styled_chunk_struct_ctor),
                &[
                    JValue::Object(&text_jstring).as_jni(),
                    JValue::Object(&text_style).as_jni(),
                ],
            )
            .expect("Failed to create StyledChunkStruct")
        };

        env.set_object_array_element(&chunk_array, i as jsize, &styled_chunk)
            .expect("Failed to set chunk array element");
    }

    // Create StyledStrStruct with the chunk array
    unsafe {
        env.new_object_unchecked(
            &classes.styled_str_struct_class,
            jni::objects::JMethodID::from_raw(classes.styled_str_struct_ctor),
            &[JValue::Object(&chunk_array).as_jni()],
        )
        .expect("Failed to create StyledStrStruct")
    }
}

/// Read PickerItems computed value and return Java array of PickerItemStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedPickerItems<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobjectArray {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui_core::id::Id;
    use waterui_form::picker::PickerItem;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<Vec<PickerItem<Id>>>>(
            computed_ptr,
            "readComputedPickerItems",
            "computed",
        )
    };
    let items: Vec<PickerItem<Id>> = computed.get();

    let picker_item_class = env
        .find_class("dev/waterui/android/runtime/PickerItemStruct")
        .expect("PickerItemStruct class not found");

    let array = env
        .new_object_array(items.len() as jsize, &picker_item_class, JObject::null())
        .expect("Failed to create picker items array");

    for (i, item) in items.into_iter().enumerate() {
        let ffi = item.into_ffi();
        let tag_id: i32 = ffi.tag.inner;
        let content_ptr = ffi.content.content as jlong;

        // PickerItemStruct(tag: Int, label: StyledStrStruct)
        // But the Rust FFI gives us tag (WuiId = i64) and content (WuiText = Computed<StyledStr> ptr)
        // Kotlin expects tag: Int, so we truncate
        // Kotlin expects label: StyledStrStruct, but we have a computed ptr
        // Let's read the computed to get the actual StyledStr
        let styled_str = {
            use waterui_text::styled::StyledStr;
            let computed = unsafe {
                &*require_jlong_ptr::<WuiComputed<StyledStr>>(
                    content_ptr,
                    "readComputedPickerItems",
                    "content computed",
                )
            };
            computed.get()
        };
        let label_obj = styled_str_to_java(&mut env, styled_str);

        let item_obj = env
            .new_object(
                &picker_item_class,
                "(ILdev/waterui/android/runtime/StyledStrStruct;)V",
                &[JValue::Int(tag_id), JValue::Object(&label_obj)],
            )
            .expect("Failed to create PickerItemStruct");

        env.set_object_array_element(&array, i as jsize, &item_obj)
            .expect("Failed to set picker item array element");
    }

    array.into_raw()
}

fn menu_item_to_java<'local>(env: &mut JNIEnv<'local>, ffi: crate::WuiMenuItem) -> JObject<'local> {
    let menu_item_class = env
        .find_class("dev/waterui/android/runtime/MenuItemStruct")
        .expect("MenuItemStruct class not found");

    let label_ptr = ffi.label.content as jlong;
    if !ffi.label.paragraph_alignment.is_null() {
        unsafe {
            drop(Box::from_raw(ffi.label.paragraph_alignment));
        }
    }

    // Android currently drops semantic menu SystemIcon payloads. Cross-platform icon-pack icons are not wired
    // into the semantic menu tree yet.
    if !ffi.icon.is_null() {
        unsafe {
            drop(Box::from_raw(ffi.icon));
        }
    }

    let (key_equivalent, command, shift, option, control) = if ffi.shortcut.is_null() {
        (JObject::null(), false, false, false, false)
    } else {
        let shortcut = unsafe { Box::from_raw(ffi.shortcut) };
        let key = env
            .new_string(unsafe { shortcut.key.as_str() })
            .expect("Failed to create shortcut key string");
        (
            JObject::from(key),
            shortcut.modifiers.command,
            shortcut.modifiers.shift,
            shortcut.modifiers.option,
            shortcut.modifiers.control,
        )
    };

    env.new_object(
        &menu_item_class,
        "(IJJJJLjava/lang/String;ZZZZJ)V",
        &[
            JValue::Int(ffi.tag as jint),
            JValue::Long(label_ptr),
            JValue::Long(ffi.action as jlong),
            JValue::Long(ffi.disabled as jlong),
            JValue::Long(ffi.selected as jlong),
            JValue::Object(&key_equivalent),
            JValue::Bool(if command { 1 } else { 0 }),
            JValue::Bool(if shift { 1 } else { 0 }),
            JValue::Bool(if option { 1 } else { 0 }),
            JValue::Bool(if control { 1 } else { 0 }),
            JValue::Long(ffi.items as jlong),
        ],
    )
    .expect("Failed to create MenuItemStruct")
}

/// Read MenuItems computed value and return Java array of MenuItemStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedMenuItems<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobjectArray {
    use crate::{IntoFFI, MenuItems};
    use waterui::Signal;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<MenuItems>>(
            computed_ptr,
            "readComputedMenuItems",
            "computed",
        )
    };
    let items: MenuItems = computed.get();

    let menu_item_class = env
        .find_class("dev/waterui/android/runtime/MenuItemStruct")
        .expect("MenuItemStruct class not found");

    let items_vec: Vec<_> = items.into_iter().collect();
    let array = env
        .new_object_array(items_vec.len() as jsize, &menu_item_class, JObject::null())
        .expect("Failed to create menu items array");

    for (i, item) in items_vec.into_iter().enumerate() {
        let item_obj = menu_item_to_java(&mut env, item.into_ffi());

        env.set_object_array_element(&array, i as jsize, &item_obj)
            .expect("Failed to set menu item array element");
    }

    array.into_raw()
}

/// Read TableCols computed value and return Java array of TableColumnStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedTableCols<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobjectArray {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui::prelude::table::TableColumn;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<Vec<TableColumn>>>(
            computed_ptr,
            "readComputedTableColumns",
            "computed",
        )
    };
    let cols: Vec<TableColumn> = computed.get();

    let table_column_class = env
        .find_class("dev/waterui/android/runtime/TableColumnStruct")
        .expect("TableColumnStruct class not found");

    let array = env
        .new_object_array(cols.len() as jsize, &table_column_class, JObject::null())
        .expect("Failed to create table columns array");

    for (i, col) in cols.into_iter().enumerate() {
        let ffi = col.into_ffi();
        // TableColumnStruct(labelContentPtr: Long, rowsPtr: Long)
        // WuiTableColumn has label: WuiText (which contains content ptr) and rows: *mut WuiAnyViews
        let label_ptr = ffi.label.content as jlong;
        let rows_ptr = ffi.rows as jlong;

        let col_obj = env
            .new_object(
                &table_column_class,
                "(JJ)V",
                &[JValue::Long(label_ptr), JValue::Long(rows_ptr)],
            )
            .expect("Failed to create TableColumnStruct");

        env.set_object_array_element(&array, i as jsize, &col_obj)
            .expect("Failed to set table column array element");
    }

    array.into_raw()
}

/// Read Region computed value and return Java RegionStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedRegion<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui_map::Region;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<Region>>(computed_ptr, "readComputedRegion", "computed")
    };
    let region: Region = computed.get();
    let ffi = region.into_ffi();

    create_region_struct(
        &mut env,
        ffi.center.latitude,
        ffi.center.longitude,
        ffi.latitude_delta,
        ffi.longitude_delta,
    )
    .into_raw()
}

/// Read Annotations computed value and return Java array of AnnotationStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedAnnotations<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobjectArray {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui_map::Annotation;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<Vec<Annotation>>>(
            computed_ptr,
            "readComputedAnnotations",
            "computed",
        )
    };
    let annotations: Vec<Annotation> = computed.get();

    let annotation_class = env
        .find_class("dev/waterui/android/runtime/AnnotationStruct")
        .expect("AnnotationStruct class not found");

    let array = env
        .new_object_array(
            annotations.len() as jsize,
            &annotation_class,
            JObject::null(),
        )
        .expect("Failed to create annotations array");

    for (i, annotation) in annotations.into_iter().enumerate() {
        let ffi = annotation.into_ffi();
        let title = unsafe { ffi.title.as_str() };
        let subtitle = unsafe { ffi.subtitle.as_str() };

        let annotation_obj = create_annotation_struct(
            &mut env,
            ffi.coordinate.latitude,
            ffi.coordinate.longitude,
            title,
            subtitle,
        );

        env.set_object_array_element(&array, i as jsize, &annotation_obj)
            .expect("Failed to set annotation array element");
    }

    array.into_raw()
}

/// Read Video computed value and return Java VideoStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedVideo<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use crate::components::video::Video;
    use waterui::Signal;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<Video>>(computed_ptr, "readComputedVideo", "computed")
    };
    let video: Video = computed.get();
    let ffi = video.into_ffi();
    let url = unsafe { ffi.url.as_str() };

    create_video_struct(&mut env, url).into_raw()
}

/// Read LivePhotoSource computed value and return Java LivePhotoSourceStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedLivePhotoSource<
    'local,
>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui_media::live::LivePhotoSource;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<LivePhotoSource>>(
            computed_ptr,
            "readComputedLivePhotoSource",
            "computed",
        )
    };
    let source: LivePhotoSource = computed.get();
    let ffi = source.into_ffi();
    let image = unsafe { ffi.image.as_str() };
    let video = unsafe { ffi.video.as_str() };

    create_live_photo_source_struct(&mut env, image, video).into_raw()
}

/// Read Date computed value and return Java DateStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedDate<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use waterui::Signal;
    use waterui_form::picker::date::Date;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<Date>>(computed_ptr, "readComputedDate", "computed")
    };
    let date: Date = computed.get();
    let ffi = date.into_ffi();

    create_date_struct(&mut env, ffi.year, ffi.month as i32, ffi.day as i32).into_raw()
}

/// Read DateTime computed value and return Java DateTimeStruct.
#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_readComputedDateTime<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    computed_ptr: jlong,
) -> jobject {
    use crate::IntoFFI;
    use jiff::civil::DateTime;
    use waterui::Signal;

    let computed = unsafe {
        &*require_jlong_ptr::<WuiComputed<DateTime>>(
            computed_ptr,
            "readComputedDateTime",
            "computed",
        )
    };
    let date_time: DateTime = computed.get();
    let ffi = date_time.into_ffi();

    create_date_time_struct(
        &mut env,
        ffi.year,
        ffi.month as i32,
        ffi.day as i32,
        ffi.hour as i32,
        ffi.minute as i32,
        ffi.second as i32,
    )
    .into_raw()
}

// ============================================================================
// Watcher Guard Drop
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dropWatcherGuard<'local>(
    _env: JNIEnv<'local>,
    _class: JClass<'local>,
    guard_ptr: jlong,
) {
    unsafe {
        drop(Box::from_raw(require_jlong_ptr::<WuiWatcherGuard>(
            guard_ptr,
            "dropWatcherGuard",
            "guard",
        )))
    };
}

// ============================================================================
// Watcher Creation Functions - Full Implementation
// ============================================================================

// The watcher system allows Rust to notify Kotlin when computed values change.
// A WatcherStruct contains pointers to: data (callback), call function, drop function.
//
// Flow:
// 1. Kotlin creates WatcherCallback<T>
// 2. JNI createXxxWatcher(callback) returns WatcherStruct(dataPtr, callPtr, dropPtr)
// 3. WatcherStruct is passed to watchComputedXxx which registers with Rust signal
// 4. When value changes, Rust calls callPtr(dataPtr, value, metadata)
// 5. callPtr converts value to Java and invokes callback.onChanged(value, metadata)

use jni::JavaVM;
use std::sync::Arc;

/// Watcher data stored for each watcher. Holds the Java callback reference.
struct WatcherData {
    callback: jni::objects::GlobalRef,
    jvm: Arc<JavaVM>,
}

/// Drop function for watcher data - releases the GlobalRef.
unsafe extern "C" fn watcher_drop(data: *mut ()) {
    let _: Box<WatcherData> = unsafe { Box::from_raw(data as *mut WatcherData) };
    // WatcherData drops here, releasing GlobalRef
}

/// Helper to create WuiWatcherMetadata Java object from pointer.
fn create_metadata_object<'local>(
    env: &mut JNIEnv<'local>,
    metadata_ptr: jlong,
) -> JObject<'local> {
    let classes = crate::jni::java_classes();
    unsafe {
        env.new_object_unchecked(
            &classes.watcher_metadata_class,
            jni::objects::JMethodID::from_raw(classes.watcher_metadata_ctor),
            &[JValue::Long(metadata_ptr).as_jni()],
        )
        .expect("Failed to create WuiWatcherMetadata")
    }
}

/// Invoke the callback's onChanged method with value and metadata.
fn invoke_callback<'local>(
    env: &mut JNIEnv<'local>,
    callback: &jni::objects::GlobalRef,
    value: &JObject<'local>,
    metadata: &JObject<'local>,
) {
    env.call_method(
        callback.as_obj(),
        "onChanged",
        "(Ljava/lang/Object;Ldev/waterui/android/reactive/WuiWatcherMetadata;)V",
        &[JValue::Object(value), JValue::Object(metadata)],
    )
    .expect("Failed to call onChanged");
}

// ============================================================================
// Type-specific watcher call functions
// ============================================================================

/// Call function for Bool watcher.
unsafe extern "C" fn watcher_call_bool(
    data: *mut (),
    value: bool,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    // Box the boolean
    let bool_class = env
        .find_class("java/lang/Boolean")
        .expect("Boolean class not found");
    let java_value = env
        .call_static_method(
            &bool_class,
            "valueOf",
            "(Z)Ljava/lang/Boolean;",
            &[JValue::Bool(if value { 1 } else { 0 })],
        )
        .expect("Failed to box boolean")
        .l()
        .expect("Expected object");

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for Int watcher.
unsafe extern "C" fn watcher_call_int(
    data: *mut (),
    value: i32,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let int_class = env
        .find_class("java/lang/Integer")
        .expect("Integer class not found");
    let java_value = env
        .call_static_method(
            &int_class,
            "valueOf",
            "(I)Ljava/lang/Integer;",
            &[JValue::Int(value)],
        )
        .expect("Failed to box integer")
        .l()
        .expect("Expected object");

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for Double watcher.
unsafe extern "C" fn watcher_call_double(
    data: *mut (),
    value: f64,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let double_class = env
        .find_class("java/lang/Double")
        .expect("Double class not found");
    let java_value = env
        .call_static_method(
            &double_class,
            "valueOf",
            "(D)Ljava/lang/Double;",
            &[JValue::Double(value)],
        )
        .expect("Failed to box double")
        .l()
        .expect("Expected object");

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for Float watcher.
unsafe extern "C" fn watcher_call_float(
    data: *mut (),
    value: f32,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let float_class = env
        .find_class("java/lang/Float")
        .expect("Float class not found");
    let java_value = env
        .call_static_method(
            &float_class,
            "valueOf",
            "(F)Ljava/lang/Float;",
            &[JValue::Float(value)],
        )
        .expect("Failed to box float")
        .l()
        .expect("Expected object");

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for String watcher.
unsafe extern "C" fn watcher_call_string(
    data: *mut (),
    value: crate::WuiStr,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let str_value = unsafe { value.as_str() };
    let java_string = env
        .new_string(str_value)
        .expect("Failed to create Java string");

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_string, &metadata);
}

/// Call function for AnyView watcher (returns Long pointer).
unsafe extern "C" fn watcher_call_any_view(
    data: *mut (),
    value: *mut crate::WuiAnyView,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let long_class = env
        .find_class("java/lang/Long")
        .expect("Long class not found");
    let java_value = env
        .call_static_method(
            &long_class,
            "valueOf",
            "(J)Ljava/lang/Long;",
            &[JValue::Long(value as jlong)],
        )
        .expect("Failed to box long")
        .l()
        .expect("Expected object");

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for ResolvedColor watcher.
unsafe extern "C" fn watcher_call_resolved_color(
    data: *mut (),
    value: crate::color::WuiResolvedColor,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let java_value = create_resolved_color_struct(
        &mut env,
        value.red,
        value.green,
        value.blue,
        value.opacity,
        value.headroom,
    );

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for ResolvedFont watcher.
unsafe extern "C" fn watcher_call_resolved_font(
    data: *mut (),
    value: crate::components::text::WuiResolvedFont,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let family = unsafe { value.family.as_str() };
    let java_value = create_resolved_font_struct(&mut env, value.size, value.weight as i32, family);

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for Video watcher.
unsafe extern "C" fn watcher_call_video(
    data: *mut (),
    value: crate::components::video::WuiComputedVideo,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let url = unsafe { value.url.as_str() };
    let java_value = create_video_struct(&mut env, url);

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for LivePhotoSource watcher.
unsafe extern "C" fn watcher_call_live_photo_source(
    data: *mut (),
    value: crate::components::media::WuiLivePhotoSource,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let image = unsafe { value.image.as_str() };
    let video = unsafe { value.video.as_str() };
    let java_value = create_live_photo_source_struct(&mut env, image, video);

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for StyledStr watcher.
unsafe extern "C" fn watcher_call_styled_str(
    data: *mut (),
    value: crate::components::text::WuiStyledStr,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    // Convert WuiStyledStr to Java StyledStrStruct
    let java_value = wui_styled_str_to_java(&mut env, &value);

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Convert WuiStyledStr reference to Java StyledStrStruct.
fn wui_styled_str_to_java<'local>(
    env: &mut JNIEnv<'local>,
    ffi: &crate::components::text::WuiStyledStr,
) -> JObject<'local> {
    let chunks_slice = ffi.chunks.as_slice();

    let classes = crate::jni::java_classes();

    let chunk_array = env
        .new_object_array(
            chunks_slice.len() as jsize,
            &classes.styled_chunk_struct_class,
            JObject::null(),
        )
        .expect("Failed to create chunk array");

    for (i, chunk) in chunks_slice.iter().enumerate() {
        let style = &chunk.style;
        let text_style = unsafe {
            env.new_object_unchecked(
                &classes.text_style_struct_class,
                jni::objects::JMethodID::from_raw(classes.text_style_struct_ctor),
                &[
                    JValue::Long(style.font as jlong).as_jni(),
                    JValue::Bool(if style.italic { 1 } else { 0 }).as_jni(),
                    JValue::Bool(if style.underline { 1 } else { 0 }).as_jni(),
                    JValue::Bool(if style.strikethrough { 1 } else { 0 }).as_jni(),
                    JValue::Long(style.foreground as jlong).as_jni(),
                    JValue::Long(style.background as jlong).as_jni(),
                ],
            )
            .expect("Failed to create TextStyleStruct")
        };

        let text_str = unsafe { chunk.text.as_str() };
        let text_jstring = env
            .new_string(text_str)
            .expect("Failed to create text string");

        let styled_chunk = unsafe {
            env.new_object_unchecked(
                &classes.styled_chunk_struct_class,
                jni::objects::JMethodID::from_raw(classes.styled_chunk_struct_ctor),
                &[
                    JValue::Object(&text_jstring).as_jni(),
                    JValue::Object(&text_style).as_jni(),
                ],
            )
            .expect("Failed to create StyledChunkStruct")
        };

        env.set_object_array_element(&chunk_array, i as jsize, &styled_chunk)
            .expect("Failed to set chunk array element");
    }

    unsafe {
        env.new_object_unchecked(
            &classes.styled_str_struct_class,
            jni::objects::JMethodID::from_raw(classes.styled_str_struct_ctor),
            &[JValue::Object(&chunk_array).as_jni()],
        )
        .expect("Failed to create StyledStrStruct")
    }
}

/// Call function for Region watcher.
unsafe extern "C" fn watcher_call_region(
    data: *mut (),
    value: crate::components::map::WuiRegion,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let java_value = create_region_struct(
        &mut env,
        value.center.latitude,
        value.center.longitude,
        value.latitude_delta,
        value.longitude_delta,
    );

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for Date watcher.
unsafe extern "C" fn watcher_call_date(
    data: *mut (),
    value: crate::components::form::WuiDate,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let java_value = create_date_struct(&mut env, value.year, value.month as i32, value.day as i32);

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for DateTime watcher.
unsafe extern "C" fn watcher_call_date_time(
    data: *mut (),
    value: crate::components::form::WuiDateTime,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let java_value = create_date_time_struct(
        &mut env,
        value.year,
        value.month as i32,
        value.day as i32,
        value.hour as i32,
        value.minute as i32,
        value.second as i32,
    );

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(&mut env, &watcher_data.callback, &java_value, &metadata);
}

/// Call function for WindowState watcher (uses i32).
unsafe extern "C" fn watcher_call_window_state(
    data: *mut (),
    value: i32,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    watcher_call_int(data, value, metadata_ptr);
}

/// Call function for CursorStyle watcher (uses i32).
unsafe extern "C" fn watcher_call_cursor_style(
    data: *mut (),
    value: i32,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    watcher_call_int(data, value, metadata_ptr);
}

/// Call function for HorizontalAlignment watcher (uses i32).
unsafe extern "C" fn watcher_call_horizontal_alignment(
    data: *mut (),
    value: i32,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    watcher_call_int(data, value, metadata_ptr);
}

// Array-based watchers need special handling for PickerItems, TableCols, Annotations

/// Call function for PickerItems watcher.
unsafe extern "C" fn watcher_call_picker_items(
    data: *mut (),
    value: crate::array::WuiArray<crate::components::form::WuiPickerItem>,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let items_slice = value.as_slice();
    let classes = crate::jni::java_classes();

    let array = env
        .new_object_array(
            items_slice.len() as jsize,
            &classes.picker_item_struct_class,
            JObject::null(),
        )
        .expect("Failed to create picker items array");

    for (i, item) in items_slice.iter().enumerate() {
        let tag_id = item.tag.inner;
        let content_ptr = item.content.content as jlong;

        // Read the styled str from the computed
        use waterui::Signal;
        use waterui_text::styled::StyledStr;
        let computed = unsafe {
            &*require_jlong_ptr::<crate::reactive::WuiComputed<StyledStr>>(
                content_ptr,
                "watchComputedPickerItems",
                "content computed",
            )
        };
        let styled_str = computed.get();
        let label_obj = styled_str_to_java(&mut env, styled_str);

        let item_obj = unsafe {
            env.new_object_unchecked(
                &classes.picker_item_struct_class,
                jni::objects::JMethodID::from_raw(classes.picker_item_struct_ctor),
                &[
                    JValue::Int(tag_id).as_jni(),
                    JValue::Object(&label_obj).as_jni(),
                ],
            )
            .expect("Failed to create PickerItemStruct")
        };

        env.set_object_array_element(&array, i as jsize, &item_obj)
            .expect("Failed to set picker item array element");
    }

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(
        &mut env,
        &watcher_data.callback,
        &unsafe { JObject::from_raw(array.into_raw()) },
        &metadata,
    );
}

unsafe extern "C" fn watcher_call_menu_items(
    data: *mut (),
    value: crate::array::WuiArray<crate::WuiMenuItem>,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let items_slice = value.as_slice();
    let menu_item_class = env
        .find_class("dev/waterui/android/runtime/MenuItemStruct")
        .expect("MenuItemStruct class not found");

    let array = env
        .new_object_array(
            items_slice.len() as jsize,
            &menu_item_class,
            JObject::null(),
        )
        .expect("Failed to create menu items array");

    for (i, item) in items_slice.iter().enumerate() {
        let item_obj = menu_item_to_java(&mut env, item.clone());
        env.set_object_array_element(&array, i as jsize, &item_obj)
            .expect("Failed to set menu item array element");
    }

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(
        &mut env,
        &watcher_data.callback,
        &unsafe { JObject::from_raw(array.into_raw()) },
        &metadata,
    );
}

/// Call function for TableCols watcher.
unsafe extern "C" fn watcher_call_table_cols(
    data: *mut (),
    value: crate::array::WuiArray<crate::components::table::WuiTableColumn>,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let cols_slice = value.as_slice();
    let classes = crate::jni::java_classes();

    let array = env
        .new_object_array(
            cols_slice.len() as jsize,
            &classes.table_column_struct_class,
            JObject::null(),
        )
        .expect("Failed to create table columns array");

    for (i, col) in cols_slice.iter().enumerate() {
        let label_ptr = col.label.content as jlong;
        let rows_ptr = col.rows as jlong;

        let col_obj = unsafe {
            env.new_object_unchecked(
                &classes.table_column_struct_class,
                jni::objects::JMethodID::from_raw(classes.table_column_struct_ctor),
                &[
                    JValue::Long(label_ptr).as_jni(),
                    JValue::Long(rows_ptr).as_jni(),
                ],
            )
            .expect("Failed to create TableColumnStruct")
        };

        env.set_object_array_element(&array, i as jsize, &col_obj)
            .expect("Failed to set table column array element");
    }

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(
        &mut env,
        &watcher_data.callback,
        &unsafe { JObject::from_raw(array.into_raw()) },
        &metadata,
    );
}

/// Call function for Annotations watcher.
unsafe extern "C" fn watcher_call_annotations(
    data: *mut (),
    value: crate::array::WuiArray<crate::components::map::WuiAnnotation>,
    metadata_ptr: *mut crate::reactive::WuiWatcherMetadata,
) {
    let watcher_data = unsafe { &*(data as *const WatcherData) };
    let mut env = watcher_data
        .jvm
        .attach_current_thread()
        .expect("Failed to attach JVM thread");

    let annotations_slice = value.as_slice();
    let classes = crate::jni::java_classes();

    let array = env
        .new_object_array(
            annotations_slice.len() as jsize,
            &classes.annotation_struct_class,
            JObject::null(),
        )
        .expect("Failed to create annotations array");

    for (i, annotation) in annotations_slice.iter().enumerate() {
        let title = unsafe { annotation.title.as_str() };
        let subtitle = unsafe { annotation.subtitle.as_str() };

        let annotation_obj = create_annotation_struct(
            &mut env,
            annotation.coordinate.latitude,
            annotation.coordinate.longitude,
            title,
            subtitle,
        );

        env.set_object_array_element(&array, i as jsize, &annotation_obj)
            .expect("Failed to set annotation array element");
    }

    let metadata = create_metadata_object(&mut env, metadata_ptr as jlong);
    invoke_callback(
        &mut env,
        &watcher_data.callback,
        &unsafe { JObject::from_raw(array.into_raw()) },
        &metadata,
    );
}

// ============================================================================
// Watcher creation functions with proper call trampolines
// ============================================================================

/// Generic watcher creation with type-specific call function.
fn create_watcher_struct_with_call<'local, F>(
    env: &mut JNIEnv<'local>,
    callback: &JObject<'local>,
    call_fn: F,
) -> JObject<'local>
where
    F: Fn() -> *const (),
{
    let jvm = Arc::new(env.get_java_vm().expect("Failed to get JavaVM"));

    let global_callback = env
        .new_global_ref(callback)
        .expect("Failed to create global ref for callback");

    let watcher_data = Box::new(WatcherData {
        callback: global_callback,
        jvm,
    });
    let data_ptr = Box::into_raw(watcher_data) as jlong;

    let classes = crate::jni::java_classes();

    let call_ptr = call_fn() as jlong;
    let drop_ptr = watcher_drop as *const () as jlong;

    unsafe {
        env.new_object_unchecked(
            &classes.watcher_struct_class,
            jni::objects::JMethodID::from_raw(classes.watcher_struct_ctor),
            &[
                JValue::Long(data_ptr).as_jni(),
                JValue::Long(call_ptr).as_jni(),
                JValue::Long(drop_ptr).as_jni(),
            ],
        )
        .expect("Failed to create WatcherStruct")
    }
}

/// Macro to generate watcher creation functions with proper call trampolines.
macro_rules! jni_create_watcher_typed {
    ($name:ident, $call_fn:ident) => {
        pastey::paste! {
            #[unsafe(no_mangle)]
            pub extern "system" fn [<Java_dev_waterui_android_ffi_WatcherJni_create $name Watcher>]<'local>(
                mut env: JNIEnv<'local>,
                _class: JClass<'local>,
                callback: JObject<'local>,
            ) -> jobject {
                create_watcher_struct_with_call(&mut env, &callback, || $call_fn as *const ()).into_raw()
            }
        }
    };
}

// Generate watcher creation functions with proper type-specific call functions
jni_create_watcher_typed!(Bool, watcher_call_bool);
jni_create_watcher_typed!(Int, watcher_call_int);
jni_create_watcher_typed!(Double, watcher_call_double);
jni_create_watcher_typed!(Float, watcher_call_float);
jni_create_watcher_typed!(String, watcher_call_string);
jni_create_watcher_typed!(AnyView, watcher_call_any_view);
jni_create_watcher_typed!(Video, watcher_call_video);
jni_create_watcher_typed!(LivePhotoSource, watcher_call_live_photo_source);
jni_create_watcher_typed!(StyledStr, watcher_call_styled_str);
jni_create_watcher_typed!(ResolvedColor, watcher_call_resolved_color);
jni_create_watcher_typed!(ResolvedFont, watcher_call_resolved_font);
jni_create_watcher_typed!(PickerItems, watcher_call_picker_items);
jni_create_watcher_typed!(MenuItems, watcher_call_menu_items);
jni_create_watcher_typed!(WindowState, watcher_call_window_state);
jni_create_watcher_typed!(TableCols, watcher_call_table_cols);
jni_create_watcher_typed!(Region, watcher_call_region);
jni_create_watcher_typed!(Annotations, watcher_call_annotations);
jni_create_watcher_typed!(CursorStyle, watcher_call_cursor_style);
jni_create_watcher_typed!(HorizontalAlignment, watcher_call_horizontal_alignment);
jni_create_watcher_typed!(Date, watcher_call_date);
jni_create_watcher_typed!(DateTime, watcher_call_date_time);

// ============================================================================
// Dynamic Connect
// ============================================================================

#[unsafe(no_mangle)]
pub extern "system" fn Java_dev_waterui_android_ffi_WatcherJni_dynamicConnect<'local>(
    mut env: JNIEnv<'local>,
    _class: JClass<'local>,
    dynamic_ptr: jlong,
    watcher: JObject<'local>,
) {
    let (data_ptr, call_ptr, drop_ptr) = crate::jni::extract_watcher_struct(&mut env, &watcher);

    let call_fn: unsafe extern "C" fn(
        *mut (),
        *mut crate::WuiAnyView,
        *mut crate::reactive::WuiWatcherMetadata,
    ) = unsafe { core::mem::transmute(call_ptr as *const ()) };
    let drop_fn: unsafe extern "C" fn(*mut ()) =
        unsafe { core::mem::transmute(drop_ptr as *const ()) };

    let watcher = unsafe {
        crate::reactive::WuiWatcher::<waterui::AnyView>::new(data_ptr as *mut (), call_fn, drop_fn)
    };

    // Ownership of the watcher is transferred to Rust; it will be dropped when the
    // Dynamic view is dropped, triggering drop_fn to release the Java callback.
    let watcher_ptr = Box::into_raw(Box::new(watcher));
    unsafe {
        crate::components::dynamic::waterui_dynamic_connect(
            dynamic_ptr as *mut crate::components::dynamic::WuiDynamic,
            watcher_ptr,
        );
    }
}
