[package]
name = "waterui-form"
version = "0.1.0"
edition = "2024"

[dependencies]
waterui-core.workspace = true
waterui-reactive.workspace = true
waterui-text.workspace = true
uniffi.workspace = true