[package]
name = "waterui-reactive"
version = "0.1.0"
edition = "2024"

[dependencies]
waterui-task.workspace = true
waterui-str.workspace = true
paste = "1.0"

[dependencies.uniffi]
version = "0.29"
