[package]
name = "waterui-reactive"
version = "0.1.0"
edition = "2021"

[dependencies]
waterui-str = { path = "../waterui-str" }
waterui-task = { path = "../waterui-task" }
async-channel = "2.2.1"
pin-project-lite = "0.2.15"
