//! Terminal (TUI) entry point for {{ ctx.app_display_name }}.
//!
//! Experimental backend — regenerated by `water run --tui`; edits are discarded.

fn main() {
    // `run_app` installs the executors before the closure runs — environment
    // composition may already spawn reactive work.
    waterui_tui::run_app(|| {
        let env = waterui::configure_environment!(waterui::env::Environment::new());
        {{ ctx.crate_name_ident() }}::app(env)
    })
    .expect("failed to run the WaterUI terminal backend");
}
