[package]
name = "waterui-graphics"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Graphic components for WaterUI"
keywords = ["graphics", "2d", "ui", "waterui"]
categories = ["gui"]

[features]
default = []

[dependencies]
waterui-core.workspace = true
waterui-str.workspace = true
nami.workspace = true
filtrate-core.workspace = true
pastey.workspace = true
wgpu.workspace = true
vello.workspace = true
kurbo.workspace = true
peniko.workspace = true
bytemuck = "1.25"
encase.workspace = true
glam = "0.29"
tracing.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "avif", "tiff"] }
png = "0.18"
parking_lot = "0.12"
pollster = "0.4"
inventory = "0.3"
dirs = "5.0"
rayon = "1.11"
mp4parse = "0.17"

[build-dependencies]
naga = { version = "27", features = ["wgsl-in"] }

[lints]
workspace = true
