//! Android platform build and package utilities.
//!
//! This module provides utility functions for building and packaging Android apps.
//! These functions are used by `AndroidBackend` to implement the `Backend` trait.

use std::path::{Path, PathBuf};

use eyre::{self, WrapErr as _, bail};
use smol::{fs, unblock};
use target_lexicon::{
    Aarch64Architecture, Architecture, BinaryFormat, Environment, OperatingSystem, Triple, Vendor,
};

use std::str::FromStr;

use crate::{
    android::toolchain::{AndroidNdk, AndroidSdk, Java, Kotlin, java_proxy_properties_from_env},
    platform::TargetPlatform,
    toolchain::Host,
};

fn gradle_cmd(
    host: &Host,
    gradlew: &Path,
    backend_path: &Path,
    tasks: &[&str],
) -> smol::process::Command {
    let mut cmd = host.command(gradlew);
    cmd.args(tasks).arg("--project-dir").arg(backend_path);
    cmd
}

/// Run the Gradle wrapper inside `backend_path` on `tasks`, wiring the JDK
/// and SDK the toolchain resolves plus any corporate proxy properties, and
/// bail with the captured output when the build fails. The shared tail of
/// every Gradle invocation the CLI drives — app packaging and the embedded
/// library's assemble/publish alike.
pub(crate) async fn run_gradle_tasks(
    host: &Host,
    backend_path: &Path,
    tasks: &[&str],
    extra_envs: &[(&str, String)],
) -> eyre::Result<()> {
    // The scaffold ships the wrapper scripts and properties but not the jar
    // — the repository carries no binary files, so the jar is materialized
    // here, the first point a Gradle task can run. A project generated by an
    // older CLI (jar embedded then) or one whose jar a cleanup removed is
    // healed the same way.
    crate::project_model::gradle_wrapper::ensure(host, backend_path)
        .await
        .wrap_err_with(|| format!("preparing the Gradle wrapper in {}", backend_path.display()))?;

    let gradlew = backend_path.join(if cfg!(windows) {
        "gradlew.bat"
    } else {
        "gradlew"
    });

    // Set JAVA_HOME to Android Studio's bundled JDK to avoid JDK version conflicts
    // (e.g., Homebrew's JDK 25 is not supported by Android Gradle Plugin)
    let mut cmd = gradle_cmd(host, &gradlew, backend_path, tasks);
    if let Some(java_home) = Java::detect_home(host).await {
        cmd.env("JAVA_HOME", java_home);
    }
    if let Some(sdk_path) = AndroidSdk::detect_path(host) {
        cmd.env("ANDROID_HOME", &sdk_path)
            .env("ANDROID_SDK_ROOT", &sdk_path);
    }
    // WATERUI_ANDROID_UNSIGNED is the package step's signal to skip the
    // generated release signingConfig; a value inherited from the caller's
    // own environment would silently unsigned an asked-for signed package, so
    // only the value extra_envs supplies may reach Gradle.
    cmd.env_remove(crate::android::signing::UNSIGNED_ENV);
    for (key, value) in extra_envs {
        cmd.env(key, value);
    }
    apply_gradle_proxy_env(host, &mut cmd)?;

    let output = cmd.output().await?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        bail!(
            "Gradle build failed in {}:\n{}\n{}",
            backend_path.display(),
            stdout.trim(),
            stderr.trim()
        );
    }
    Ok(())
}

fn apply_gradle_proxy_env(host: &Host, cmd: &mut smol::process::Command) -> eyre::Result<()> {
    let proxy_properties = java_proxy_properties_from_env(host)?;
    if proxy_properties.is_empty() {
        return Ok(());
    }

    cmd.args(&proxy_properties);

    let mut gradle_opts = proxy_properties.join(" ");
    if let Some(existing) = host.env_string("GRADLE_OPTS")
        && !existing.trim().is_empty()
    {
        gradle_opts.push(' ');
        gradle_opts.push_str(&existing);
    }
    cmd.env("GRADLE_OPTS", gradle_opts);
    Ok(())
}

/// Get the NDK host tag based on the current machine's OS and architecture.
///
/// On Apple Silicon, prefer the native `darwin-arm64` toolchain when present,
/// falling back to `darwin-x86_64` for older Android NDK releases (Rosetta).
fn ndk_host_tag(ndk_path: &Path) -> &'static str {
    use target_lexicon::{Architecture, OperatingSystem, Triple};

    let host = Triple::host();

    match (&host.operating_system, &host.architecture) {
        (OperatingSystem::Darwin(_), Architecture::Aarch64(_)) => {
            let native = ndk_path
                .join("toolchains/llvm/prebuilt")
                .join("darwin-arm64");
            if native.exists() {
                "darwin-arm64"
            } else {
                "darwin-x86_64"
            }
        }
        (OperatingSystem::Darwin(_), _) => "darwin-x86_64",
        (OperatingSystem::Windows, _) => "windows-x86_64",
        // NDK doesn't have native ARM64 Linux builds
        (OperatingSystem::Linux, _) => "linux-x86_64",
        _ => panic!("Unsupported host triple for Android NDK: {host}"),
    }
}

fn ndk_bin_dir(ndk_path: &Path) -> PathBuf {
    ndk_path
        .join("toolchains/llvm/prebuilt")
        .join(ndk_host_tag(ndk_path))
        .join("bin")
}

/// An LLVM binary tool (`llvm-strip`, `llvm-readelf`, …) from the NDK's
/// prebuilt host toolchain — the same `prebuilt/<host-tag>/bin` directory
/// the linker and `ar` resolve from, with the host's executable suffix
/// (`llvm-strip.exe` on Windows).
///
/// # Errors
/// Returns an error when the NDK's bin directory does not ship `tool` —
/// naming the tool and where it was looked for.
pub(crate) fn ndk_llvm_tool(ndk_path: &Path, tool: &str) -> eyre::Result<PathBuf> {
    let path = ndk_bin_dir(ndk_path).join(format!("{tool}{}", std::env::consts::EXE_SUFFIX));
    if path.is_file() {
        Ok(path)
    } else {
        eyre::bail!(
            "the NDK at {} ships no {tool} — expected {}",
            ndk_path.display(),
            path.display()
        )
    }
}

/// Get the NDK ar path.
fn ndk_ar_path(ndk_path: &Path) -> PathBuf {
    ndk_bin_dir(ndk_path).join("llvm-ar")
}

fn ndk_clang_path(ndk_path: &Path, abi: AndroidAbi, cxx: bool, api_level: u32) -> PathBuf {
    let suffix = if cxx { "clang++" } else { "clang" };
    ndk_bin_dir(ndk_path).join(format!("{}{api_level}-{suffix}", abi.ndk_target()))
}

/// Get the NDK clang linker path for the given ABI.
fn ndk_linker_path(ndk_path: &Path, abi: AndroidAbi, api_level: u32) -> PathBuf {
    ndk_clang_path(ndk_path, abi, false, api_level)
}

/// Create a wrapper `CMake` toolchain file that sets `ANDROID_ABI` before including
/// the NDK's toolchain. This is required because cmake-rs doesn't pass `ANDROID_ABI`
/// as a -D define, causing the NDK toolchain to default to armeabi-v7a.
///
/// Returns the path to the created wrapper toolchain file.
async fn create_android_toolchain_wrapper(
    host: &Host,
    ndk_path: &Path,
    abi: AndroidAbi,
    api_level: u32,
) -> eyre::Result<PathBuf> {
    // Create wrapper in a temp directory that persists for the build
    let wrapper_dir = host.temp_dir().join("waterui-cmake-toolchains");
    fs::create_dir_all(&wrapper_dir).await?;

    let wrapper_path = wrapper_dir.join(format!("android-{}.cmake", abi.as_str()));
    let ndk_toolchain = ndk_path.join("build/cmake/android.toolchain.cmake");

    let content = format!(
        include_str!("android_toolchain_wrapper.cmake.tpl"),
        abi = abi.as_str(),
        api_level = api_level,
        ndk_toolchain = ndk_toolchain.display(),
        asm_compiler = ndk_clang_path(ndk_path, abi, false, api_level).display(),
    );
    crate::templates::write_file_if_changed(&wrapper_path, content.as_bytes()).await?;

    Ok(wrapper_path)
}

/// Get the NDK clang++ (C++ compiler) path for the given ABI.
fn ndk_cxx_path(ndk_path: &Path, abi: AndroidAbi, api_level: u32) -> PathBuf {
    ndk_clang_path(ndk_path, abi, true, api_level)
}

/// Get the path to `libc++_shared.so` in the NDK.
///
/// NDK r23+ ships it under `sysroot/usr/lib/<triple>/`, while older Android
/// NDK releases used `sources/cxx-stl/llvm-libc++/libs/<abi>/`.
pub(crate) fn ndk_libcxx_path(ndk_path: &Path, abi: AndroidAbi) -> PathBuf {
    let new_path = ndk_path
        .join("toolchains/llvm/prebuilt")
        .join(ndk_host_tag(ndk_path))
        .join("sysroot/usr/lib")
        .join(abi.ndk_libcxx_triple())
        .join("libc++_shared.so");

    if new_path.exists() {
        return new_path;
    }

    ndk_path
        .join("sources/cxx-stl/llvm-libc++/libs")
        .join(abi.as_str())
        .join("libc++_shared.so")
}

/// The linker flag that aligns every produced ELF's `LOAD` segments to 16 KB
/// pages — the largest page size Android ships (Pixel 9 class) and Google
/// Play's packaging requirement. The app and every preview module it
/// `dlopen`s must carry the same flag.
pub(crate) const ANDROID_MAX_PAGE_SIZE_LINK_ARG: &str = "-Clink-arg=-Wl,-z,max-page-size=16384";

/// Represents an Android platform for a specific architecture.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AndroidAbi {
    /// ARM64 (arm64-v8a) - modern Android devices
    Arm64V8a,
    /// `x86_64` - emulators on Intel/AMD
    X86_64,
    /// `ARMv7` (armeabi-v7a) - older 32-bit devices
    ArmeabiV7a,
    /// x86 - older 32-bit emulators
    X86,
}

/// Error returned when parsing an unsupported Android ABI string.
#[derive(Debug, thiserror::Error)]
#[error("Unsupported Android ABI: {abi}")]
pub struct UnsupportedAndroidAbi {
    abi: String,
}

impl FromStr for AndroidAbi {
    type Err = UnsupportedAndroidAbi;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "arm64-v8a" => Ok(Self::Arm64V8a),
            "x86_64" => Ok(Self::X86_64),
            "armeabi-v7a" => Ok(Self::ArmeabiV7a),
            "x86" => Ok(Self::X86),
            other => Err(UnsupportedAndroidAbi {
                abi: other.to_string(),
            }),
        }
    }
}

impl AndroidAbi {
    #[must_use]
    /// Android ABI string used by the Android toolchain (e.g. `arm64-v8a`).
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Arm64V8a => "arm64-v8a",
            Self::X86_64 => "x86_64",
            Self::ArmeabiV7a => "armeabi-v7a",
            Self::X86 => "x86",
        }
    }

    #[must_use]
    /// Target triple prefix used by the NDK toolchain binaries (clang, clang++).
    pub const fn ndk_target(self) -> &'static str {
        match self {
            Self::Arm64V8a => "aarch64-linux-android",
            Self::X86_64 => "x86_64-linux-android",
            Self::ArmeabiV7a => "armv7a-linux-androideabi",
            Self::X86 => "i686-linux-android",
        }
    }

    #[must_use]
    /// Target triple used by NDK sysroot libc++ paths.
    pub const fn ndk_libcxx_triple(self) -> &'static str {
        match self {
            Self::Arm64V8a => "aarch64-linux-android",
            Self::X86_64 => "x86_64-linux-android",
            Self::ArmeabiV7a => "arm-linux-androideabi",
            Self::X86 => "i686-linux-android",
        }
    }

    /// The ABI a Rust target triple names — the inverse of
    /// [`AndroidPlatform::triple`], so call sites holding a triple never keep
    /// a second copy of the architecture mapping.
    #[must_use]
    pub const fn from_triple(triple: &Triple) -> Option<Self> {
        match triple.architecture {
            Architecture::Aarch64(_) => Some(Self::Arm64V8a),
            Architecture::X86_64 => Some(Self::X86_64),
            Architecture::Arm(target_lexicon::ArmArchitecture::Armv7) => Some(Self::ArmeabiV7a),
            Architecture::X86_32(target_lexicon::X86_32Architecture::I686) => Some(Self::X86),
            _ => None,
        }
    }
}

/// Represents an Android platform for a specific ABI.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AndroidPlatform {
    abi: AndroidAbi,
}

#[derive(Debug)]
pub(crate) struct AndroidBuildContext {
    pub(crate) abi: AndroidAbi,
    pub(crate) ndk_path: PathBuf,
    pub(crate) linker: PathBuf,
    pub(crate) ar: PathBuf,
    pub(crate) cxx: PathBuf,
    pub(crate) target_underscore: String,
    pub(crate) target_upper: String,
    pub(crate) java_home: PathBuf,
    pub(crate) java_bin_dir: PathBuf,
    pub(crate) kotlin_compiler: PathBuf,
    pub(crate) kotlin_bin_dir: PathBuf,
    pub(crate) kotlin_home: PathBuf,
    pub(crate) sdk_path: PathBuf,
    pub(crate) android_jar: PathBuf,
    pub(crate) wrapper_toolchain: PathBuf,
    pub(crate) android_platform: String,
}

impl AndroidPlatform {
    /// Create a new Android platform with the specified ABI.
    #[must_use]
    pub const fn new(abi: AndroidAbi) -> Self {
        Self { abi }
    }

    /// Create an Android platform for arm64-v8a (most common modern Android devices).
    #[must_use]
    pub const fn arm64() -> Self {
        Self {
            abi: AndroidAbi::Arm64V8a,
        }
    }

    /// Create an Android platform for `x86_64` (emulators on Intel/AMD).
    #[must_use]
    pub const fn x86_64() -> Self {
        Self {
            abi: AndroidAbi::X86_64,
        }
    }

    #[must_use]
    /// Return the ABI for this platform.
    pub const fn abi(&self) -> AndroidAbi {
        self.abi
    }

    #[must_use]
    /// Return the ABI string for this platform.
    pub const fn abi_str(&self) -> &'static str {
        self.abi.as_str()
    }

    /// Create an Android platform from an ABI string.
    ///
    /// # Errors
    /// Returns an error if the ABI is not supported.
    pub fn try_from_abi(abi: &str) -> eyre::Result<Self> {
        let abi = AndroidAbi::from_str(abi).map_err(|e| eyre::eyre!(e))?;
        Ok(Self { abi })
    }
}

/// All supported Android ABIs.
pub const ALL_ABIS: &[AndroidAbi] = &[
    AndroidAbi::Arm64V8a,
    AndroidAbi::X86_64,
    AndroidAbi::ArmeabiV7a,
    AndroidAbi::X86,
];

impl AndroidPlatform {
    /// Returns all supported Android platforms (all architectures).
    #[must_use]
    pub fn all() -> Vec<Self> {
        ALL_ABIS.iter().copied().map(Self::new).collect()
    }

    /// Get the target triple for this Android platform.
    #[must_use]
    pub const fn triple(&self) -> Triple {
        let (architecture, environment) = match self.abi {
            AndroidAbi::Arm64V8a => (
                Architecture::Aarch64(Aarch64Architecture::Aarch64),
                Environment::Android,
            ),
            AndroidAbi::X86_64 => (Architecture::X86_64, Environment::Android),
            // rustc's armv7 Android target carries the `androideabi`
            // environment (`armv7-linux-androideabi`); `android` alone names
            // no target.
            AndroidAbi::ArmeabiV7a => (
                Architecture::Arm(target_lexicon::ArmArchitecture::Armv7),
                Environment::Androideabi,
            ),
            AndroidAbi::X86 => (
                Architecture::X86_32(target_lexicon::X86_32Architecture::I686),
                Environment::Android,
            ),
        };
        Triple {
            architecture,
            vendor: Vendor::Unknown,
            operating_system: OperatingSystem::Linux,
            environment,
            binary_format: BinaryFormat::Elf,
        }
    }

    /// List available Android Virtual Devices (emulators) on `host`.
    ///
    /// # Errors
    /// Returns an error if the emulator tool is not found.
    pub async fn list_avds(host: &Host) -> eyre::Result<Vec<String>> {
        let emulator_path = AndroidSdk::emulator_path(host)
            .ok_or_else(|| eyre::eyre!("Android emulator not found"))?;

        let output = host.output(&emulator_path, ["-list-avds"]).await?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        let avds: Vec<String> = stdout
            .lines()
            .filter(|line| !line.is_empty())
            .map(String::from)
            .collect();

        Ok(avds)
    }
}

pub(crate) async fn resolve_android_build_context(
    host: &Host,
    abi: AndroidAbi,
    triple: &Triple,
    api_level: u32,
) -> eyre::Result<AndroidBuildContext> {
    let ndk_path = AndroidNdk::detect_path(host).ok_or_else(|| {
        eyre::eyre!("Android NDK not found. Please install it via Android Studio.")
    })?;
    let linker = ndk_linker_path(&ndk_path, abi, api_level);
    let ar = ndk_ar_path(&ndk_path);
    let cxx = ndk_cxx_path(&ndk_path, abi, api_level);
    // The toolchain gate only proves the NDK's host toolchain executes; the
    // wrapper for the framework's floor is a separate fact, and a missing one
    // otherwise surfaces minutes later as a linker cargo cannot find.
    for wrapper in [&linker, &cxx] {
        if !wrapper.is_file() {
            eyre::bail!(
                "the Android NDK at {} ships no compiler wrapper for API {api_level} \
                 ({}); the framework's android-min-api-level needs an NDK that targets it",
                ndk_path.display(),
                wrapper.display()
            );
        }
    }
    let target_underscore = triple.to_string().replace('-', "_");
    let target_upper = target_underscore.to_uppercase();
    let (java_home, java_bin_dir) = resolve_java_home(host).await?;
    let (kotlin_compiler, kotlin_bin_dir, kotlin_home) = resolve_kotlin_home(host).await?;
    let (sdk_path, android_jar) = resolve_android_sdk_paths(host).await?;
    let wrapper_toolchain =
        create_android_toolchain_wrapper(host, &ndk_path, abi, api_level).await?;

    Ok(AndroidBuildContext {
        abi,
        ndk_path,
        linker,
        ar,
        cxx,
        target_underscore,
        target_upper,
        java_home,
        java_bin_dir,
        kotlin_compiler,
        kotlin_bin_dir,
        kotlin_home,
        sdk_path,
        android_jar,
        wrapper_toolchain,
        android_platform: format!("android-{api_level}"),
    })
}

async fn resolve_java_home(host: &Host) -> eyre::Result<(PathBuf, PathBuf)> {
    let java_home = Java::detect_home(host).await.ok_or_else(|| {
        eyre::eyre!(
            "Java runtime not found. Install a JDK (or Android Studio JBR), then re-run `water doctor --fix`."
        )
    })?;
    let java_bin_dir = java_home.join("bin");
    Ok((java_home, java_bin_dir))
}

async fn resolve_kotlin_home(host: &Host) -> eyre::Result<(PathBuf, PathBuf, PathBuf)> {
    let kotlin_compiler = Kotlin::detect_path(host).await.ok_or_else(|| {
        eyre::eyre!(
            "Kotlin compiler (kotlinc) not found. Install Android Studio or set `KOTLIN_HOME`, then re-run `water doctor`."
        )
    })?;
    let kotlin_bin_dir = kotlin_compiler.parent().map(PathBuf::from).ok_or_else(|| {
        eyre::eyre!(
            "Failed to determine Kotlin bin directory from `{}`.",
            kotlin_compiler.display()
        )
    })?;
    let kotlin_home = kotlin_bin_dir.parent().map(PathBuf::from).ok_or_else(|| {
        eyre::eyre!(
            "Failed to determine KOTLIN_HOME from `{}`.",
            kotlin_bin_dir.display()
        )
    })?;
    Ok((kotlin_compiler, kotlin_bin_dir, kotlin_home))
}

/// Resolve the SDK root and its newest `android.jar` on `host`.
///
/// `AndroidSdk::android_jar_path` walks `platforms/` on disk, so the whole
/// resolution runs on a blocking thread instead of the executor.
async fn resolve_android_sdk_paths(host: &Host) -> eyre::Result<(PathBuf, PathBuf)> {
    let host = host.clone();
    smol::unblock(move || {
        let sdk_path = AndroidSdk::detect_path(&host).ok_or_else(|| {
            eyre::eyre!("Android SDK not found. Please install it via Android Studio.")
        })?;
        let android_jar = AndroidSdk::android_jar_path(&host).ok_or_else(|| {
            eyre::eyre!(
                "Android platforms not found in SDK at {}. Install an Android platform (SDK) in Android Studio.",
                sdk_path.display()
            )
        })?;
        Ok((sdk_path, android_jar))
    })
    .await
}
/// The `PATH` an Android cargo invocation runs under: the resolved JDK and
/// Kotlin compiler bin directories ahead of the host's, so NDK-side build
/// scripts find the same toolchain the doctor verified.
pub(crate) async fn android_path_env(
    host: &Host,
    context: &AndroidBuildContext,
) -> eyre::Result<std::ffi::OsString> {
    let current_path = host
        .env("PATH")
        .ok_or_else(|| eyre::eyre!("PATH environment variable is not set"))?;
    let mut paths: Vec<PathBuf> = std::env::split_paths(&current_path).collect();
    paths.insert(0, context.java_bin_dir.clone());
    paths.insert(0, context.kotlin_bin_dir.clone());
    std::env::join_paths(paths).map_err(|error| {
        eyre::eyre!("Failed to construct PATH for Java/Kotlin compiler resolution: {error}")
    })
}

/// The environment every Cargo invocation targeting an Android ABI needs:
/// the NDK clang as linker and `cc`/`cxx`/`ar`, the SDK/NDK locations build
/// scripts probe, the `CMake` toolchain file for native dependencies, and the
/// `pkg-config` cross overrides.
///
/// The support app and the preview module it loads must compile their shared
/// dependency graph identically, so both take their environment from this one
/// list rather than each spelling it out.
pub(crate) fn android_cargo_envs(
    context: &AndroidBuildContext,
    triple: &Triple,
) -> Vec<(String, std::ffi::OsString)> {
    [
        (
            format!("CARGO_TARGET_{}_LINKER", context.target_upper),
            context.linker.as_os_str().to_os_string(),
        ),
        (
            format!("CARGO_TARGET_{}_AR", context.target_upper),
            context.ar.as_os_str().to_os_string(),
        ),
        (
            format!("CC_{}", context.target_underscore),
            context.linker.as_os_str().to_os_string(),
        ),
        (
            format!("CXX_{}", context.target_underscore),
            context.cxx.as_os_str().to_os_string(),
        ),
        (
            format!("AR_{}", context.target_underscore),
            context.ar.as_os_str().to_os_string(),
        ),
        (
            "ANDROID_NDK".to_string(),
            context.ndk_path.as_os_str().to_os_string(),
        ),
        (
            "ANDROID_NDK_HOME".to_string(),
            context.ndk_path.as_os_str().to_os_string(),
        ),
        (
            "ANDROID_NDK_ROOT".to_string(),
            context.ndk_path.as_os_str().to_os_string(),
        ),
        (
            "ANDROID_HOME".to_string(),
            context.sdk_path.as_os_str().to_os_string(),
        ),
        (
            "ANDROID_SDK_ROOT".to_string(),
            context.sdk_path.as_os_str().to_os_string(),
        ),
        (
            "ANDROID_JAR".to_string(),
            context.android_jar.as_os_str().to_os_string(),
        ),
        (
            "JAVA_HOME".to_string(),
            context.java_home.as_os_str().to_os_string(),
        ),
        (
            "KOTLIN_HOME".to_string(),
            context.kotlin_home.as_os_str().to_os_string(),
        ),
        (
            "KOTLINC".to_string(),
            context.kotlin_compiler.as_os_str().to_os_string(),
        ),
        (
            "CMAKE_TOOLCHAIN_FILE".to_string(),
            context.wrapper_toolchain.as_os_str().to_os_string(),
        ),
        (
            format!("CMAKE_TOOLCHAIN_FILE_{}", context.target_underscore),
            context.wrapper_toolchain.as_os_str().to_os_string(),
        ),
        (
            "CMAKE_ASM_COMPILER".to_string(),
            context.linker.as_os_str().to_os_string(),
        ),
        ("ANDROID_ABI".to_string(), context.abi.as_str().into()),
        (
            "ANDROID_PLATFORM".to_string(),
            context.android_platform.clone().into(),
        ),
        ("PKG_CONFIG_ALLOW_CROSS".to_string(), "1".into()),
        (
            format!("PKG_CONFIG_ALLOW_CROSS_{}", context.target_underscore),
            "1".into(),
        ),
        (format!("PKG_CONFIG_ALLOW_CROSS_{triple}"), "1".into()),
    ]
    .into_iter()
    .collect()
}

/// True when any `.so` staged in `output_dir` lists `libc++_shared.so` in its
/// `DT_NEEDED` entries.
///
/// An unreadable or unparsable library counts as needing it: including the STL
/// when in doubt is the same behavior the packaging had before, and a corrupt
/// native library is going to fail loudly on the device anyway.
pub(crate) async fn staged_libs_need_libcxx(output_dir: &Path) -> eyre::Result<bool> {
    let output_dir = output_dir.to_path_buf();
    unblock(move || {
        let mut needs = false;
        for entry in std::fs::read_dir(&output_dir)? {
            let path = entry?.path();
            if path.extension() != Some(std::ffi::OsStr::new("so")) {
                continue;
            }
            let needed = std::fs::read(&path)
                .ok()
                .and_then(|data| elf_needs_libcxx(&data))
                .unwrap_or_else(|| {
                    tracing::warn!(
                        library = %path.display(),
                        "could not parse staged library; assuming it needs libc++_shared.so"
                    );
                    true
                });
            needs |= needed;
        }
        Ok(needs)
    })
    .await
}

/// `true` when the ELF data's dynamic section `DT_NEEDED`s `libc++_shared.so`;
/// `None` when the data is not a parseable ELF image at all.
fn elf_needs_libcxx(data: &[u8]) -> Option<bool> {
    use object::read::elf::{Dyn as _, ElfFile, FileHeader};

    fn scan<Elf>(data: &[u8]) -> Option<bool>
    where
        Elf: FileHeader<Endian = object::Endianness>,
    {
        let file = ElfFile::<Elf>::parse(data).ok()?;
        let endian = file.endian();
        let sections = file.elf_section_table();
        let (dyns, strings_index) = sections.dynamic(endian, data).ok()??;
        let strings = sections.strings(endian, data, strings_index).ok()?;
        Some(dyns.iter().any(|d| {
            d.tag32(endian) == Some(object::elf::DT_NEEDED)
                && d.string(endian, strings).ok() == Some(&b"libc++_shared.so"[..])
        }))
    }

    scan::<object::elf::FileHeader64<object::Endianness>>(data)
        .or_else(|| scan::<object::elf::FileHeader32<object::Endianness>>(data))
}

// ============================================================================
// Platform Support Check
// ============================================================================

/// Check if a platform is supported by the Android backend.
#[must_use]
pub const fn is_android_platform(platform: TargetPlatform) -> bool {
    matches!(platform, TargetPlatform::Android)
}

#[cfg(test)]
mod tests {
    use super::elf_needs_libcxx;

    #[test]
    fn elf_needs_libcxx_rejects_non_elf_data() {
        // Verified against real NDK binaries during development (a clang++
        // shared object reports `Some(true)`, `libc++_shared.so` itself
        // `Some(false)`); the committed test covers only the reject path so it
        // needs no fixtures.
        assert_eq!(elf_needs_libcxx(b"not an elf"), None);
        assert_eq!(elf_needs_libcxx(&[]), None);
        assert_eq!(elf_needs_libcxx(&[0x7f, b'E', b'L', b'F']), None);
    }
}
