[package]
name = "snackbar-example"
version = "0.1.0"
edition = "2024"
authors = ["Lexo Liu"]
description = "Snackbar example for WaterUI framework"
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords = ["ui", "framework", "example", "snackbar"]
categories = ["gui"]
publish = false

[features]
dev = ["waterui/dynamic_linking"]

[dependencies]
waterui = { version = "0.2.1", path = "../../../..", default-features = false }
waterui-icons-material-icon.workspace = true
