[package]
name = "hydrolysis"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
waterui-core.workspace = true
waterui = { version = "0.2.1", path = "../..", default-features = false }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nami.workspace = true
waterui-graphics.workspace = true
waterui-canvas.workspace = true
waterui-text.workspace = true
waterui-icon.workspace = true
waterui-shape.workspace = true
waterui-video.workspace = true
waterui-map.workspace = true
waterui-webview.workspace = true
waterui-layout.workspace = true
waterui-controls.workspace = true
waterui-form.workspace = true
waterui-backend-core.workspace = true
waterkit-clipboard.workspace = true
vello.workspace = true
parley.workspace = true
wgpu.workspace = true
pollster.workspace = true
executor-core.workspace = true
async-task = "4.7"
native-executor.workspace = true
winit = { version = "0.30", optional = true }
accesskit = { version = "0.24", optional = true }
accesskit_winit = { version = "0.32.1", optional = true }

[build-dependencies]
cfg_aliases = "0.2.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
fontique = "0.7"
js-sys = "0.3"
serde = { workspace = true, features = ["derive"] }
serde_json = "1"
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-time = "1"
web-sys = { version = "0.3", optional = true, features = [
    "Response",
    "CompositionEvent",
    "CssStyleDeclaration",
    "Document",
    "DomRect",
    "Element",
    "Event",
    "EventTarget",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "KeyboardEvent",
    "Node",
    "PointerEvent",
    "WheelEvent",
    "Window",
] }

[features]
default = []
accessibility = ["dep:accesskit"]
testing = []
winit = ["accessibility", "dep:winit", "dep:accesskit_winit"]
web = ["dep:wasm-bindgen", "dep:wasm-bindgen-futures", "dep:web-sys"]
[package.metadata.cargo-machete]
ignored = ["cfg_aliases", "waterui-backend-core"]
