[package]
name = "waterdata"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
serde = "1.0.210"
waterui-reactive = { path = "../waterui-reactive" }
waterui = { path = "../waterui" }
futures-lite = "2.3.0"
