[package]
name = "waterui-barcode"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
readme = "../../README.md"
repository = "https://github.com/water-rs/waterui"
description = "WaterUI barcode and QR code component"
keywords = ["gpu", "barcode", "qrcode", "waterui"]
categories = ["graphics", "rendering", "gui"]
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
waterui-core.workspace = true
waterui-graphics.workspace = true
waterui-image.workspace = true
wgpu.workspace = true
bytemuck = { version = "1", features = ["derive"] }
fast_qr = "0.12"
barcoders = { version = "2.0.0", default-features = false }

[dev-dependencies]
waterui.workspace = true
waterui-testing.workspace = true
