//! CLI command implementations.

use std::path::PathBuf;

use clap::ValueEnum;
use dialoguer::{Confirm, theme::ColorfulTheme};

use crate::shell::Shell;
use crate::{note, success, warn};
use waterui_cli::{
    android::device::{AndroidDecision, AndroidTarget},
    apple::backend::AppleBackend,
    backend::reinit_backend,
    gtk4::backend::Gtk4Backend,
    hydrolysis::backend::HydrolysisBackend,
    platform::TargetBackend as LibTargetBackend,
    project::Project,
    toolchain::{Host, sccache::Sccache},
    utils::sccache_install_hint,
    winui::backend::WinUiBackend,
};

/// Target backend (how the app is built and rendered).
///
/// Shared by every command that takes `--backend`; commands accepting a
/// narrower or wider set (`water clean` adds `all`) define their own.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum TargetBackend {
    /// Apple backend (UIKit/AppKit).
    Apple,
    /// Android backend (Android Views).
    Android,
    /// GTK4 backend (Linux only, experimental).
    Gtk4,
    /// Hydrolysis backend (self-drawn renderer).
    Hydrolysis,
    /// `WinUI` backend (Windows only, experimental).
    #[value(name = "winui")]
    WinUi,
}

impl TargetBackend {
    /// Convert a resolved library backend to its terminal representation.
    pub const fn from_lib(backend: LibTargetBackend) -> Self {
        match backend {
            LibTargetBackend::Apple => Self::Apple,
            LibTargetBackend::Android => Self::Android,
            LibTargetBackend::Gtk4 => Self::Gtk4,
            LibTargetBackend::Hydrolysis => Self::Hydrolysis,
            LibTargetBackend::WinUi => Self::WinUi,
        }
    }

    /// Whether the backend is experimental — shipped without full testing
    /// ahead of milestone releases — so selecting it asks for confirmation.
    pub const fn is_experimental(self) -> bool {
        matches!(self, Self::Gtk4 | Self::WinUi)
    }

    /// The backend's display name.
    pub const fn label(self) -> &'static str {
        match self {
            Self::Apple => "Apple",
            Self::Android => "Android",
            Self::Gtk4 => "GTK4",
            Self::Hydrolysis => "Hydrolysis",
            Self::WinUi => "WinUI",
        }
    }

    /// The library backend enum this CLI value selects.
    pub const fn lib_backend(self) -> LibTargetBackend {
        match self {
            Self::Apple => LibTargetBackend::Apple,
            Self::Android => LibTargetBackend::Android,
            Self::Gtk4 => LibTargetBackend::Gtk4,
            Self::Hydrolysis => LibTargetBackend::Hydrolysis,
            Self::WinUi => LibTargetBackend::WinUi,
        }
    }
}

/// Whether the host environment permits routing builds through `sccache`.
fn sccache_allowed(host: &Host) -> bool {
    if let Some(value) = host.env("WATERUI_DISABLE_SCCACHE") {
        let value = value.to_string_lossy().trim().to_ascii_lowercase();
        if matches!(value.as_str(), "1" | "true" | "yes" | "on") {
            return false;
        }
    }
    // Respect explicit wrapper from caller (e.g. passthrough wrapper in constrained envs).
    host.env("RUSTC_WRAPPER").is_none()
}

/// Locate `sccache` for compilation caching, noting on the shell when it is
/// skipped or missing.
async fn detect_sccache_path(shell: &Shell, host: &Host) -> Option<PathBuf> {
    if !sccache_allowed(host) {
        note!(
            shell,
            "Skipping sccache (explicit wrapper or WATERUI_DISABLE_SCCACHE is set)"
        );
        return None;
    }

    let sccache = Sccache;
    sccache.path(host).await.map_or_else(
        |_| {
            warn!(
                shell,
                "sccache not found. Build efficiency may be reduced. Install with: {}",
                sccache_install_hint()
            );
            None
        },
        Some,
    )
}

/// Generate or refresh the CLI-managed backend project `backend` builds
/// with, in the project's managed build cache.
///
/// Apple and Android are generated by [`Project::open`] for the platforms the
/// command selected; here the Apple project is only re-rendered when its
/// inputs changed. The other backends are generated on demand, after the
/// framework channel is checked to distribute every scaffold package they
/// link.
async fn ensure_generated_backend(
    shell: &Shell,
    project: Project,
    backend: TargetBackend,
) -> eyre::Result<Project> {
    let needs_generation = match backend {
        TargetBackend::Apple => {
            project.apple_backend().is_some()
                && AppleBackend::requires_regeneration(&project).await?
        }
        TargetBackend::Android => false,
        TargetBackend::Gtk4 => Gtk4Backend::requires_regeneration(&project).await?,
        TargetBackend::Hydrolysis => HydrolysisBackend::requires_regeneration(&project).await?,
        TargetBackend::WinUi => WinUiBackend::requires_regeneration(&project).await?,
    };
    if !needs_generation {
        return Ok(project);
    }
    project
        .require_distributable_backend(backend.lib_backend())
        .await?;
    let spinner = shell.spinner(format!("Generating the {} backend...", backend.label()));
    match backend {
        TargetBackend::Apple => {
            reinit_backend::<AppleBackend>(&project).await?;
        }
        TargetBackend::Android => {}
        TargetBackend::Gtk4 => {
            reinit_backend::<Gtk4Backend>(&project).await?;
        }
        TargetBackend::Hydrolysis => {
            reinit_backend::<HydrolysisBackend>(&project).await?;
        }
        TargetBackend::WinUi => {
            reinit_backend::<WinUiBackend>(&project).await?;
        }
    }
    if let Some(pb) = spinner {
        pb.finish_and_clear();
    }
    success!(shell, "{} backend generated", backend.label());
    Ok(project)
}

/// Confirm that the user accepts running an experimental backend.
///
/// Experimental backends are not fully tested ahead of milestone releases, so
/// every use warns once and requires an explicit second confirmation: the
/// command's `--yes` flag in scripts and CI, or a prompt everywhere else.
/// Returns `Ok(false)` when the user declines at the prompt so the caller can
/// exit quietly; a non-interactive invocation without `yes` is an error.
fn confirm_experimental_backend(
    shell: &Shell,
    backend_name: &str,
    yes: bool,
) -> eyre::Result<bool> {
    warn!(
        shell,
        "The {backend_name} backend is experimental and is not fully tested ahead of milestone releases"
    );
    if yes {
        return Ok(true);
    }
    if !shell.is_interactive() {
        eyre::bail!(
            "the {backend_name} backend is experimental; pass --yes to confirm it in non-interactive environments"
        );
    }
    let confirmed = Confirm::with_theme(&ColorfulTheme::default())
        .with_prompt(format!(
            "Continue with the experimental {backend_name} backend?"
        ))
        .default(false)
        .interact()?;
    if !confirmed {
        warn!(shell, "Cancelled");
        return Ok(false);
    }
    Ok(true)
}

pub mod bench;
pub mod build;
pub mod channel;
pub mod clean;
pub mod completions;
pub mod create;
pub mod device;
pub mod devices;
pub mod doctor;
pub mod fetch;
pub mod gc;
pub mod init;
pub mod inspector;
pub mod mcp;
pub mod package;
pub mod preview;
pub mod run;
pub mod update;
pub mod web;

/// Ask which device to use among `candidates`, `(label, id)` pairs in the
/// order a picker shows them. Non-interactive runs cannot pick, so they
/// fail with the candidate list.
pub fn prompt_for_device(
    shell: &Shell,
    prompt: &str,
    candidates: &[(&str, &str)],
    spinner: Option<&indicatif::ProgressBar>,
) -> eyre::Result<usize> {
    if !shell.is_terminal() {
        return Err(waterui_cli::device::ambiguous_device_error(
            candidates.iter().copied(),
        ));
    }
    let labels: Vec<&str> = candidates.iter().map(|(label, _)| *label).collect();
    let pick = || {
        dialoguer::Select::with_theme(&ColorfulTheme::default())
            .with_prompt(prompt)
            .items(&labels)
            .default(0)
            .interact()
    };
    // The scan spinner would redraw over the prompt; hide it while the user
    // answers.
    Ok(spinner.map_or_else(pick, |pb| pb.suspend(pick))?)
}

/// Resolve the Android target a command runs on through the shared library
/// selection ([`AndroidTarget::select`]): `--device` names it, the
/// remembered last-used device wins while it is still present, an
/// interactive terminal picks among the rest, and a non-interactive one
/// fails naming every candidate.
///
/// `memory_key` is the `last_used_device` slot the choice is recorded
/// under — see [`waterui_cli::water_dir::device_memory_key`]; `None` for a
/// selection that keeps no memory.
pub async fn select_android_target(
    shell: &Shell,
    host: &Host,
    memory_key: Option<&str>,
    device_id: Option<&str>,
    spinner: Option<&indicatif::ProgressBar>,
) -> eyre::Result<AndroidTarget> {
    let remembered = match memory_key {
        Some(key) => waterui_cli::water_dir::last_used_device(host, key).await,
        None => None,
    };
    let selection = AndroidTarget::select(host, device_id, remembered.as_deref()).await?;
    if let Some(stale) = &selection.stale {
        warn!(shell, "Last-used device \"{stale}\" is not available");
    }
    let (target, picked) = match selection.decision {
        AndroidDecision::Resolved(target) => (target, false),
        AndroidDecision::Ambiguous(candidates) => {
            let options: Vec<(&str, &str)> = candidates
                .iter()
                .map(|candidate| (candidate.label(), candidate.id()))
                .collect();
            let index = prompt_for_device(shell, "Select an Android device", &options, spinner)?;
            (
                candidates
                    .into_iter()
                    .nth(index)
                    .expect("the picker answers a listed index")
                    .into_target(),
                true,
            )
        }
    };
    // An explicit name, a pick, and a resolution that repaired stale memory
    // are the choices worth remembering.
    if let Some(key) = memory_key
        && (picked || selection.stale.is_some() || device_id.is_some())
    {
        waterui_cli::water_dir::record_last_used_device(host, key, target.id()).await;
    }
    Ok(target)
}

/// Parse a viewport size from a `WIDTHxHEIGHT` string into whole pixels.
fn parse_viewport(s: &str) -> eyre::Result<(u32, u32)> {
    let parts: Vec<&str> = s.split('x').collect();
    if parts.len() != 2 {
        eyre::bail!("Invalid viewport format: expected WIDTHxHEIGHT (e.g., 390x844)");
    }

    let width: u32 = parts[0]
        .parse()
        .map_err(|_| eyre::eyre!("Invalid viewport width"))?;
    let height: u32 = parts[1]
        .parse()
        .map_err(|_| eyre::eyre!("Invalid viewport height"))?;

    if width == 0 {
        eyre::bail!("Invalid viewport width: must be positive");
    }
    if height == 0 {
        eyre::bail!("Invalid viewport height: must be positive");
    }

    Ok((width, height))
}

#[cfg(test)]
mod tests {
    use super::confirm_experimental_backend;
    use crate::shell::Shell;

    #[test]
    fn experimental_backend_yes_flag_confirms_without_prompt() {
        // A non-interactive shell never prompts; --yes must still pass.
        let shell = Shell::new(false);
        assert!(!shell.is_interactive());
        assert!(
            confirm_experimental_backend(&shell, "GTK4", true).expect("--yes confirms the gate")
        );
    }

    #[test]
    fn experimental_backend_non_interactive_without_yes_is_an_error() {
        let shell = Shell::new(false);
        let err = confirm_experimental_backend(&shell, "GTK4", false)
            .expect_err("non-interactive use without --yes must fail");
        assert!(err.to_string().contains("--yes"));
    }
}
