//! The component ports this backend owns.
//!
//! One module per claimed view type: each registers its handler on the
//! dispatcher through [`crate::registry`]. Everything a module needs beyond
//! the [`crate::contract`] is a `cocoa-ui` addition, never a reactivity type
//! crossing into the kit.

#[cfg(feature = "accessibility_identifier")]
pub mod accessibility_identifier;
#[cfg(feature = "accessibility_metadata")]
pub mod accessibility_metadata;
#[cfg(feature = "anchored_overlay")]
pub mod anchored_overlay;
#[cfg(feature = "badge")]
pub mod badge;
#[cfg(feature = "border")]
pub mod border;
#[cfg(feature = "button")]
pub mod button;
#[cfg(feature = "clip_shape")]
pub mod clip_shape;
#[cfg(feature = "color_picker")]
pub mod color_picker;
#[cfg(feature = "container")]
pub mod container;
#[cfg(feature = "context_menu")]
pub mod context_menu;
#[cfg(any(test, feature = "button", feature = "slider"))]
pub mod control_size;
#[cfg(feature = "cursor")]
pub mod cursor;
#[cfg(feature = "date_picker")]
pub mod date_picker;
#[cfg(feature = "draggable")]
pub mod draggable;
#[cfg(feature = "drop_destination")]
pub mod drop_destination;
#[cfg(feature = "dynamic")]
pub mod dynamic;
#[cfg(feature = "dynamic_range")]
pub mod dynamic_range;
pub mod empty;
#[cfg(any(feature = "applied_filter", feature = "view_effect"))]
pub mod filtered;
#[cfg(feature = "fixed_container")]
pub mod fixed_container;
#[cfg(feature = "focused")]
pub mod focused;
#[cfg(feature = "gesture")]
pub mod gesture;
#[cfg(feature = "glass_background")]
pub mod glass_background;
#[cfg(feature = "gpu_surface")]
pub mod gpu_surface;
#[cfg(feature = "hittable")]
pub mod hittable;
#[cfg(feature = "ignore_safe_area")]
pub mod ignore_safe_area;
#[cfg(feature = "image")]
pub mod image;
#[cfg(feature = "layer_transform")]
pub mod layer_transform;
#[cfg(feature = "layout_priority")]
pub mod layout_priority;
#[cfg(feature = "lifecycle_hook")]
pub mod lifecycle_hook;
#[cfg(feature = "list")]
pub mod list;
#[cfg(feature = "map")]
pub mod map;
#[cfg(feature = "material_background")]
pub mod material_background;
#[cfg(feature = "menu")]
pub mod menu;
#[cfg(any(feature = "menu", feature = "context_menu"))]
mod menu_items;
#[cfg(feature = "multi_date_picker")]
pub mod multi_date_picker;
#[cfg(feature = "navigation")]
pub mod navigation;
#[cfg(feature = "offset")]
pub mod offset;
#[cfg(feature = "on_event")]
pub mod on_event;
#[cfg(feature = "on_key_press")]
pub mod on_key_press;
#[cfg(feature = "opacity")]
pub mod opacity;
#[cfg(feature = "picker")]
pub mod picker;
#[cfg(feature = "picture")]
pub mod picture;
#[cfg(feature = "plain")]
pub mod plain;
#[cfg(feature = "progress")]
pub mod progress;
#[cfg(feature = "resolved_color")]
pub mod resolved_color;
#[cfg(feature = "resolved_gradient")]
pub mod resolved_gradient;
#[cfg(feature = "resolved_shape")]
pub mod resolved_shape;
#[cfg(feature = "retain")]
pub mod retain;
#[cfg(feature = "rotation")]
pub mod rotation;
#[cfg(feature = "scale")]
pub mod scale;
#[cfg(feature = "scroll")]
pub mod scroll;
#[cfg(feature = "secure")]
pub mod secure;
#[cfg(feature = "secure_field")]
pub mod secure_field;
#[cfg(feature = "shadow")]
pub mod shadow;
#[cfg(feature = "slider")]
pub mod slider;
#[cfg(feature = "spacer")]
pub mod spacer;
#[cfg(feature = "stepper")]
pub mod stepper;
#[cfg(feature = "table")]
pub mod table;
#[cfg(feature = "text")]
pub mod text;
#[cfg(feature = "text_field")]
pub mod text_field;
#[cfg(feature = "toggle")]
pub mod toggle;
#[cfg(any(feature = "video", feature = "video_player"))]
pub mod video;
#[cfg(feature = "view_renderer")]
pub mod view_renderer;
#[cfg(feature = "webview")]
pub mod webview;
#[cfg(feature = "with_env")]
pub mod with_env;
