#!/usr/bin/env python3
"""Renderer boundary check for the Vello -> Cherenkov migration (issue #205).

Every reference to a Vello-owned type or crate outside the quarantined files
is tracked in `scripts/renderer_boundary_baseline.json`, keyed by file,
enclosing item and token. A reference is rejected when:

- it sits in a file the baseline does not list at all;
- it sits in an item the baseline does not list for that file;
- its token did not appear in the baseline at that item (this is what
  catches "deleted one `vello::Scene`, added one `vello::peniko::BlendMode`";
  removing references is always allowed, adding or moving is not);
- it comes through an import alias (`use vello::kurbo::Affine as X` makes
  every `X::` use a Vello reference at the use site), or
- it comes through a renamed Cargo dependency (`foo = { package = "vello" }`
  makes `foo::` a Vello reference and `foo` itself a manifest reference).

The baseline is generated on purpose; it is the inventory of what the
migration has not ported yet. Regenerate it only when a P-step removed
references: `python3 scripts/check_renderer_boundary.py --write-baseline`.

When `strict` is set in the baseline (flipped by the final cutover step),
*any* Vello reference in source or resolved Cargo metadata fails the check —
including test-only and dev-dependency references — and the quarantine list
is ignored.

Exit status: 0 = the boundary held; 1 = violations; 2 = could not run.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = Path(__file__).with_name("renderer_boundary_baseline.json")

# Directories and files scanned for source-level references.
SCAN_DIRS = ("src", "tests", "examples", "benches")
SCAN_FILES = ("build.rs", "Cargo.toml")

# A Vello reference is any `vello*` crate token. `vello_cpu`/`vello_common`/
# `vello_encoding`/`vello_hybrid` are the same fork family and equally banned
# outside the quarantine; `vello_cpu` is quarantined internally for the
# shadow rasterizer but may not be named outside its own crate usage sites.
VELLO_TOKEN = re.compile(r"\bvello(?:_[a-z_]+)?\b(?:::\s*[A-Za-z_][A-Za-z0-9_]*)*")

# `use vello::kurbo::Affine as A` (or brace lists) -> alias identifiers that
# make later `A::` path heads count as Vello references in this file.
USE_ALIAS = re.compile(
    r"\buse\s+vello(?:_[a-z_]+)?(?:::[^;]*)?\bas\s+([A-Za-z_][A-Za-z0-9_]*)"
)
USE_GLOBE_ALIAS = re.compile(
    r"\bas\s+([A-Za-z_][A-Za-z0-9_]*)\b"
)

# Manifest dep renamed to the real crate: `foo = { package = "vello" }` ->
# `foo` is a dep key whose crate ident appears in source as `foo::`.
MANIFEST_RENAMED_DEP = re.compile(
    r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{[^}]*\bpackage\s*=\s*\"(vello[^\"]*)\"",
    re.MULTILINE,
)

# Enclosing-item tracker: the nearest preceding item keyword on its own
# logical line. This is a boundary *inventory*, not a parser — it only needs
# to be stable and to tell `fn render` apart from `fn layout` so a moved
# reference does not pass as "the count merely shrank".
ITEM_HEAD = re.compile(
    r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:unsafe\s+|async\s+|const\s+|extern\s+\"[^\"]*\"\s+)*"
    r"(?:fn|struct|enum|impl|trait|mod|static|const|type|macro_rules!|macro)"
    r"\s+!?([A-Za-z_][A-Za-z0-9_]*)?"
)

COMMENT_LINE = re.compile(r"//.*?$|/\*.*?\*/", re.S)
BLOCK_COMMENT_OPEN = re.compile(r"/\*")
STRING_LITERAL = re.compile(r'"(?:\\.|[^"\\])*"')

ACTIONABLE_HINT = """\
how to fix this (another coding agent: read this):

  New drawing code must not name `vello`, `vello_cpu`, `vello_common`,
  `vello_encoding`, `vello_hybrid`, `vello_shaders`, or `vello_sparse_shaders`
  — not by `use`, not by qualified path `vello::kurbo::…`, not through a
  renamed `use` alias, and not through a renamed Cargo dependency.

  Route it through the private recording boundary instead:

      crate::renderer::recording::Recording

  `Recording` is the only drawing-call surface the renderer accepts. Its API:

      Recording::new() / .reset() / .is_empty()
      .fill(rule, transform, brush, brush_transform, shape)   // S: kurbo::Shape
      .stroke(style, transform, brush, brush_transform, shape)
      .image(&ImageBrush, Affine)
      .glyphs(GlyphRun)
      .blurred_rounded_rect(rect, radius, blur, brush)
      .push_clip(shape, transform)  /  .push_group(opacity, mix, bounds)
      .pop_scope()                  /  .append(&Recording, transform)

  Geometry and paint are plain `kurbo` and `peniko` types — import them from
  those crates directly, never through a `vello::` path. If the boundary is
  missing an operation the drawing needs, extend `recording/mod.rs` (and its
  `recording/vello.rs` backend) — do not reach for vello at the call site.

  If the reference you added is the migration porting a call site on purpose,
  the baseline must be regenerated by the migration owner — do not regenerate
  it yourself to silence this check.
"""


def strip_comments_and_strings(source: str) -> str:
    """Blank comments and string literals so tokens inside them do not count."""
    out: list[str] = []
    i = 0
    n = len(source)
    while i < n:
        if source.startswith("//", i):
            end = source.find("\n", i)
            if end == -1:
                out.append(" " * (n - i))
                break
            out.append(" " * (end - i))
            i = end
        elif source.startswith("/*", i):
            end = source.find("*/", i + 2)
            end = n if end == -1 else end + 2
            out.append("".join("\n" if c == "\n" else " " for c in source[i:end]))
            i = end
        elif source[i] == '"':
            j = i + 1
            while j < n and source[j] != '"':
                j += 2 if source[j] == "\\" else 1
            j = min(j + 1, n)
            out.append(" " * (j - i))
            i = j
        else:
            out.append(source[i])
            i += 1
    return "".join(out)


def collect_aliases(source: str) -> set[str]:
    """Identifiers bound to vello paths by `use … as Ident` in this file."""
    aliases = set(USE_ALIAS.findall(source))
    # Brace-list form: `use vello::{kurbo::Affine as A, peniko::Brush as B};`
    for stmt in re.findall(r"\buse\s+vello(?:_[a-z_]+)?::\{[^}]*\}", source):
        aliases.update(USE_GLOBE_ALIAS.findall(stmt))
    # `as _` binds no usable name; counting `\b_\b` would match every
    # placeholder pattern in the file.
    aliases.discard("_")
    return aliases


def manifest_dep_aliases(manifests: list[Path]) -> dict[str, set[str]]:
    """Dep key -> real crate renames, e.g. `myv = { package = "vello" }`."""
    aliases: dict[str, set[str]] = {}
    for path in manifests:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for key, real in MANIFEST_RENAMED_DEP.findall(text):
            aliases.setdefault(key, set()).add(real)
    return aliases


def enclosing_items(source: str):
    """Yield (start_line, name) for each item head, to bucket tokens."""
    items = []
    for lineno, line in enumerate(source.splitlines(), start=1):
        m = ITEM_HEAD.match(line)
        if m:
            items.append((lineno, m.group(1) or "<anonymous>"))
    return items


def item_of(items, lineno: int) -> str:
    name = "<top-level>"
    for start, iname in items:
        if start > lineno:
            break
        name = iname
    return name


def scan_file(path: Path, extra_tokens: set[str]) -> dict:
    """Return {item: {token: count}} for one file."""
    try:
        raw = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}
    source = strip_comments_and_strings(raw)
    tokens = [VELLO_TOKEN]
    for ident in sorted(collect_aliases(source) | extra_tokens, key=len, reverse=True):
        tokens.append(re.compile(rf"\b{re.escape(ident)}\b(?:::\s*[A-Za-z_][A-Za-z0-9_]*)*"))
    items = enclosing_items(source)
    result: dict[str, dict[str, int]] = {}
    for lineno, line in enumerate(source.splitlines(), start=1):
        normalized = re.sub(r"\s*::\s*", "::", line)
        item = item_of(items, lineno)
        for pattern in tokens:
            for match in pattern.finditer(normalized):
                token = match.group(0)
                bucket = result.setdefault(item, {})
                bucket[token] = bucket.get(token, 0) + 1
    return result


def scanned_paths(root: Path) -> list[Path]:
    paths: list[Path] = []
    for d in SCAN_DIRS:
        base = root / d
        if base.is_dir():
            paths.extend(sorted(base.rglob("*.rs")))
    for f in SCAN_FILES:
        p = root / f
        if p.is_file():
            paths.append(p)
    return paths


def manifests_under(root: Path) -> list[Path]:
    return sorted(root.rglob("Cargo.toml"))


def build_baseline(root: Path) -> dict:
    dep_aliases = manifest_dep_aliases(manifests_under(root))
    extra = set(dep_aliases)  # renamed-dep crate idents are vello tokens
    files: dict[str, dict] = {}
    for path in scanned_paths(root):
        rel = path.relative_to(root).as_posix()
        found = scan_file(path, extra)
        if found:
            files[rel] = found
    return {
        "version": 1,
        "strict": False,
        "renamed_dep_tokens": sorted(extra),
        "files": files,
    }


def load_baseline() -> dict:
    try:
        return json.loads(BASELINE_PATH.read_text(encoding="utf-8"))
    except OSError as exc:
        print(f"cannot read {BASELINE_PATH}: {exc}", file=sys.stderr)
        sys.exit(2)


def compare(root: Path, baseline: dict) -> list[str]:
    dep_aliases = manifest_dep_aliases(manifests_under(root))
    baseline_files: dict[str, dict] = baseline["files"]
    strict = bool(baseline.get("strict"))
    violations: list[str] = []

    newly_renamed = {
        k: v for k, v in dep_aliases.items() if k not in baseline.get("renamed_dep_tokens", [])
    }

    for path in scanned_paths(root):
        rel = path.relative_to(root).as_posix()
        extra = set(dep_aliases)
        found = scan_file(path, extra)
        if not found:
            continue
        if strict:
            for item, tokens in sorted(found.items()):
                for token, count in sorted(tokens.items()):
                    violations.append(
                        f"{rel}: `{item}` references `{token}` x{count} — "
                        "strict phase: no Vello reference may remain anywhere"
                    )
            continue
        if rel not in baseline_files:
            total = sum(c for t in found.values() for c in t.values())
            violations.append(
                f"{rel}: file is not in the baseline but holds {total} "
                "Vello reference(s) — new code must draw through the "
                "recording boundary"
            )
            continue
        allowed = baseline_files[rel]
        for item, tokens in sorted(found.items()):
            if item not in allowed:
                for token, count in sorted(tokens.items()):
                    violations.append(
                        f"{rel}: `{item}` has new Vello reference `{token}` "
                        f"x{count} — the baseline has no Vello in this item"
                    )
                continue
            base_counter = Counter(allowed[item])
            now_counter = Counter(tokens)
            for token, over in (now_counter - base_counter).items():
                violations.append(
                    f"{rel}: `{item}` has {base_counter.get(token, 0)} + "
                    f"{over} new `{token}` reference(s)"
                )

    if not strict:
        for key in newly_renamed:
            violations.append(
                f"Cargo manifest renames a Vello crate as `{key}` — a renamed "
                "dependency is still a Vello dependency"
            )
    else:
        metadata = subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--locked"],
            cwd=root, capture_output=True, text=True,
        )
        if metadata.returncode != 0:
            violations.append(
                "strict phase: `cargo metadata` failed; the resolved graph "
                "must be inspectable\n" + metadata.stderr.strip()[:400]
            )
        else:
            graph = json.loads(metadata.stdout)
            vello_pkgs = sorted(
                p["name"] for p in graph["packages"] if p["name"].startswith("vello")
            )
            if vello_pkgs:
                violations.append(
                    "strict phase: the resolved Cargo graph still contains "
                    + ", ".join(vello_pkgs)
                )

    return violations


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="regenerate the baseline from the current tree (migration owner only)",
    )
    args = parser.parse_args()

    if args.write_baseline:
        baseline = build_baseline(REPO_ROOT)
        # Preserve the strict flag across regeneration.
        if BASELINE_PATH.is_file():
            baseline["strict"] = bool(load_baseline().get("strict"))
        BASELINE_PATH.write_text(json.dumps(baseline, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {BASELINE_PATH} ({len(baseline['files'])} files tracked)")
        return 0

    baseline = load_baseline()
    violations = compare(REPO_ROOT, baseline)
    if not violations:
        print("renderer boundary held: no new Vello references")
        return 0
    print(f"renderer boundary violated — {len(violations)} new reference(s):\n")
    for v in violations:
        print(f"  - {v}")
    print()
    print(ACTIONABLE_HINT)
    return 1


if __name__ == "__main__":
    sys.exit(main())
