[package]
name = "waterui-macros"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Macro for WaterUI"
keywords = ["macro", "derive", "ui"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "visit-mut"] }
icu_locid = "1.5"
icu_locid_transform = "1.5"
toml = "0.8"
proc-macro-crate = "3"

[dev-dependencies]
trybuild = "1.0"
waterui.workspace = true
waterui-testing.workspace = true

[lints]
workspace = true
