// Auto-generated by WaterUI CLI - do not edit manually
import CoreText
import Foundation

enum WaterUIFonts {
    static func register() {
        let fonts: [(String, String)] = [
__FONT_ENTRIES__
        ]
        for (_, fileName) in fonts {
            // Split filename into name and extension for Bundle.main.url API
            let nsFileName = fileName as NSString
            let name = nsFileName.deletingPathExtension
            let ext = nsFileName.pathExtension

            guard let url = Bundle.main.url(forResource: name, withExtension: ext) else {
                continue
            }
            var error: Unmanaged<CFError>?
            if !CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error) {
                // Font registration failed
            }
        }
    }
}
