// Auto-generated by WaterUI CLI - do not edit manually
import CoreText
import Foundation
import os.log

private let logger = Logger(subsystem: "dev.waterui", category: "fonts")

enum WaterUIFonts {
    static func register() {
        let fonts: [(String, String)] = [
{% for entry in font_entries %}
            ("{{ entry.family_name }}", "{{ entry.file_name }}"),
{% endfor %}
        ]
        logger.debug("Registering \(fonts.count) fonts...")

        for (familyName, fileName) in fonts {
            // Split filename into name and extension for Bundle.main.url API
            let nsFileName = fileName as NSString
            let name = nsFileName.deletingPathExtension
            let ext = nsFileName.pathExtension

            guard let url = Bundle.main.url(forResource: name, withExtension: ext) else {
                fatalError("WaterUI: Font file '\(fileName)' not found in app bundle. Expected font family: '\(familyName)'")
            }

            logger.debug("Registering font: \(fileName) for family '\(familyName)' from \(url.path)")

            var error: Unmanaged<CFError>?
            if !CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error) {
                let errorDesc = error?.takeRetainedValue().localizedDescription ?? "Unknown error"
                fatalError("WaterUI: Failed to register font '\(fileName)' (\(familyName)): \(errorDesc)")
            }

            logger.debug("Successfully registered font: \(familyName)")
        }

        logger.debug("All fonts registered successfully")
    }
}
