[package]
name = "waterui-webview"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "../../../README.md"
repository = "https://github.com/water-rs/waterui"
description = "WebView component for WaterUI"
keywords = ["webview", "browser", "ui", "waterui", "gui"]
categories = ["gui"]

[dependencies]
waterui-core.workspace = true
waterui-layout.workspace = true
waterui-url.workspace = true
waterui-str.workspace = true
thiserror.workspace = true
cookie = "0.18.1"

[dev-dependencies]
hydrolysis-m3.workspace = true
waterui.workspace = true
waterui-testing.workspace = true

[lints]
workspace = true
