//! WinUI entry point for {{ ctx.app_display_name }}.
//!
//! Experimental backend — regenerated by `water`; edits are discarded.

// GUI subsystem: a console window must not appear beside the app window.
// `water run` still streams the app's stdout and stderr — inherited pipe
// handles work without a console.
#![cfg_attr(target_os = "windows", windows_subsystem = "windows")]

fn main() {
    // `run_app` installs the executors before the closure runs — environment
    // composition may already spawn reactive work.
    waterui_winui::run_app(|| {
        let env = waterui::configure_environment!(waterui::env::Environment::new());
        {{ ctx.crate_name_ident() }}::app(env)
    })
    .expect("failed to run the WaterUI WinUI backend");
}
