[package]
name = "map-example"
version = "0.1.0"
edition = "2024"
authors = ["Lexo Liu"]
description = "Map example for WaterUI framework"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["ui", "framework", "example", "map"]
categories = ["gui"]
publish = false

[features]
dev = ["waterui/dynamic_linking"]

[dependencies]
waterui = { workspace = true, features = ["map"] }
waterui-map.workspace = true
waterui-map-gpu.workspace = true
waterui-icons-lucide.workspace = true
waterui-url.workspace = true
waterkit-location.workspace = true
waterkit-permission.workspace = true
tracing.workspace = true
