[package]
name = "waterui-icons-native"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
readme = "../../README.md"
repository.workspace = true
description = "Cross-platform native icons for WaterUI"
keywords = ["icons", "native", "cross-platform", "waterui"]
categories = ["gui"]

[dependencies]
waterui-icon.workspace = true
waterui-str.workspace = true

[lints]
workspace = true
