language = "C"
[enum]
prefix_with_name = true

[export]
include = ["waterui_app","waterui_app_closure","waterui_stack_mode"]


[parse]
parse_deps = true
include = ["waterui","waterui-ffi"]


[parse.expand]
crates = ["waterui","waterui-ffi"]