language = "C"

trailer="""
waterui_env *waterui_init();
waterui_anyview *waterui_widget_main();
"""
[enum]
rename_variants = "QualifiedScreamingSnakeCase"

[export]
include = ["waterui_app","waterui_app_closure","waterui_stack_mode","waterui_fnonce","waterui_app_task"]


[parse]
parse_deps = true
include = ["waterui","waterui-ffi"]


[parse.expand]
crates = ["waterui","waterui-ffi"]